negative_tweets = \
[
    ('RT @raahandradee: Você não merece 1% do amor que eu te dei', 'negative'),
    ('RT @andradeffc: vasco fluminense e botafogo interessados no hernane ai vcs n sabem pq o futebol carioca ta esse lixo', 'negative'),
    ('A maquiagem ja vai ter virado uma bosta quando chegar na festa', 'negative'),
    ('Quanta gente chata, pelo amor de Deus!', 'negative'),
    ('Uma falta de respeito tremenda com o espaço alheio https://t.co/w0JJzZuuZ3', 'negative'),
    ('RT @falsianecobra: Dai a mina posta " odeio menina puta "  .. Fofa cade o amor próprio ?', 'negative'),
    ('É tão ruim saber, que vou pra alguma festa, lugar, você não está mais ali, pra dar opinião sobre a roupa, etc', 'negative'),
    ('@Alessandralombl agora você não tem motivos pra ter amizade com aquela lá', 'negative'),
    ('pelo amor de Deus quero q esse ano acabe logo', 'negative'),
    ('não existe amor em sp', 'negative'),
    ('RT @CaioFAbreuCitou: Não suporto meios termos. Por isso, não me doo pela metade. Não sou sua meio amiga nem seu quase amor. Ou sou tudo ou …', 'negative'),
    ('Paciência tem limite', 'negative'),
    ('Mas PORRA FALAR QUE PRA TER SUCESSO TEM QUE SER BONITO É A MAIOR MERDA QUE EU JA OUVI', 'negative'),
    ('RT @Privacidades: Nunca fui de implorar amizade. Quer ficar? Fique. Não quer? Foda-se. Mas se for para ficar, fique porque quer, não por ob…', 'negative'),
    ('Deus me dê paciência com os cancerianos da vida', 'negative'),
    ('Eu vejo que o amor é uma merda porque um bebe quando nasce já chora', 'negative'),
    ('RT @daranavy: eu digo q não gosto que façam uma merda e continuam a fazer fds santa paciência', 'negative'),
    ('RT @mariolobato: Alerta! Estamos a beira do maior retrocesso na história da Saúde Mental brasileira! https://t.co/LWITJnJN2c', 'negative'),
    ('Falta amor, falta compreensão, falta humanidade, falta Deus! E se falta Deus, falta tudo.', 'negative'),
    ('Você não era príncipe , era sapo me enganei com Marcinho kalatimbu esqueça você amor', 'negative'),
    ('mas vou me manter distante, porque não quero continuar "amizade" com a maoiria', 'negative'),
    ('Daí-me paciência com esse menino, viu?! Pqp.', 'negative'),
    ('Viado quer respeito mas... Mas o que seu idiota? E eu tendo que fazer a linha didática..', 'negative'),
    ('comprei um tênis novo, jurei amor eterno mas ele resolve que vai foder com meu calcanhar todinho', 'negative'),
    ('Eu não  respeito quem esconde. Ficar fazendo propaganda ingmorante do PT, só pode se um  dos corruptos.Então,dê-se ao respeito e cala boca!!', 'negative'),
    ('RT @naosejatrouxa: era um vez minha paciência e ela acabou, fim', 'negative'),
    ('sem essa de "é pra sempre" é amor até deixar de ser', 'negative'),
    ('RT @UOLNoticias: Acordar tarde nos fins de semana pode prejudicar sua saúde https://t.co/g67NkKr0xe', 'negative'),
    ('@olIgmagcon ah sim, eu acho essa coisa de ter crush chata e nao sinto amor por ninguem', 'negative'),
    ('RT @httpsignos: Gêmeos no amor um dia te ama e no outro te acha um F.D.P.', 'negative'),
    ('Essa gripe da amizade que surgiu do nada acabou com meus planos de hoje :(', 'negative'),
    ('RT @Eusemprelindo: Não tenho sorte no amor', 'negative'),
    ('RT @warrlly: fico imaginando eu criar minha filha com todo amor e carinho ela cresce e vira fã de felipe neto', 'negative'),
    ('ODEIO PESSOA CHICLETES E SEM PACIÊNCIA', 'negative'),
    ('Agr é um p cada lado, e o silêncio fala mas parecemos dois rivais', 'negative'),
    ('Olha p mim e me diz se alguma vez eu te deixei faltar amor..', 'negative'),
    ('RT @Renata_lopes22: Olha o que você fez, era o meu grande amor e hoje é só mais um ex', 'negative'),
    ('Mereço gente preconceituosa chorando no inbox pq desfiz amizade falando que "eu nao sei lidar com ~opiniões diferentes~"', 'negative'),
    ('Rola umas cantadas bem escrotas e eu n tenho paciência', 'negative'),
    ('RT @nacaodepre: Primeiro dispensado do Vasco foi o respeito', 'negative'),
    ('RT @arturdotcom: O bicho homem hetero tem vergonha de dizer "te amo" pra namorada e faz textão sobre sua paixão por um jogador de futebol.', 'negative'),
    ('Minha paciência ta ó', 'negative'),
    ('RT @explicandoindie: here - alessia cara eu sou uma pessimista antissocial e to pouco me fudendo pra essa festa na verdade se eu pudesse es…', 'negative'),
    ('RT @maah_romao: não tenho paciência nem para mim mesmo imagina para você', 'negative'),
    ('Aborrecendo por não poder nem bater um papinho, tomar uma cerveja, distrair...', 'negative'),
    ('@PriscilaSilva_2 muito chato tenho paciência mais não', 'negative'),
    ('preciso arruma um role p amanha.. N quero ir naqela festa, por conta daqla menina', 'negative'),
    ('Que merda fui fazer da minha vida maldito o dia q eu quis ir naquela festa', 'negative'),
    ('RT @inspirou: A minha felicidade te incomoda? Engraçado, a tua nem me interessa!', 'negative'),
    ('RT @Oliviapallito_: Gente que fica de um lado resmungando até você perde a paciência e explodir', 'negative'),
    ('Morre médico espancado em festa na USP: Segundo a universidade, serão aplicadas sanções administrativas aos or... https://t.co/V7NaMflvxM', 'negative'),
    ('Amizade é como cordas de violão, elas se quebram e podem ser remendadas, mas nunca terão novamente o mesmo som.[8867]', 'negative'),
    ('RT @stylesonthewind: "o shawn ta separando camren" vcs mesmas destruiram a amizade das duas,parem pfvr Shawn e Camila', 'negative'),
    ('RT @VoceNaoSabiaQ: O ciumento passa a vida tentando descobrir o segredo que irá destruir a sua felicidade.', 'negative'),
    ('Ao ver a foto de FHC sentado no trono golpista lembrei que Jorge Rafael Videla morreu naquela posição. https://t.co/ywMwCwhZR2', 'negative'),
    ('@Abbadon_nado eu to sem esperança tbm mas so vou saber se vou ou nao quando tiver confirmada. até la vamos nos preparar', 'negative'),
    ('@biavalente5 foi bom tu ter perdido a festa mana, foi o ò', 'negative'),
    ('Antes um recado:Tenho muita paciência mas tá por um fio #direta https://t.co/THgUWIgwwb', 'negative'),
    ('RT @noitesombria: Expectativa boa é expectativa morta.', 'negative'),
    ('RT @VoceNaoSabiaQ: Psicologicamente, depois de ser decepcionado tantas vezes, você começa a perder a esperança em tudo.', 'negative'),
    ('RT @baduum_tzz: não há namoro ou amizade alguma q dê maior desilusão que num fim de semana acordares cedo devido à puta da rotina da escola.', 'negative'),
    ('Não tenho paciência pra ter muitos grupos no whatsapp', 'negative'),
    ('RT @saulo_silvaa: Mina que fica c td mundo pra mim não tem respeito na favela', 'negative'),
    ('Não tenho paciência p esse tipo de gente, vai se fuder p lá', 'negative'),
    ('Quando surge uma esperança de melhora... Um avalanche de coisa ruim.', 'negative'),
    ('Sempre tem um pra testa sua paciência', 'negative'),
    ('RT @B00ubazar: Não sei do que fujo, a esperança pouca me resta', 'negative'),
    ('É triste ser tão novo e já achar que a vida não presta bem que alguem podia me ligar e me convidar p uma festa', 'negative'),
    ('@cissamalan Sabe de muita coisa ao meu respeito me hackeou foi ?e eu ligo pra essa sua besteira mimadinha', 'negative'),
    ('RT @g1: Noivo que comprava maconha antes de casamento é preso e perde festa https://t.co/ESd7ocGn4O https://t.co/vvRmpX5kgN', 'negative'),
    ('RT @fabio_freitas50: A felicidade de uns incomoda outros', 'negative'),
    ('Não tenho paciência para quem se faz de coitadinho.', 'negative'),
    ('RT @rwvivalarry: Harmonizer: "odeio o Shawn"', 'negative'),
    ('@ENZlNHODO15 eu tava na casa dum amigo meu, fui dormir as 7 acordei as 10, mó merda', 'negative'),
    ('não gosto de gente que fica babando ovo de gente merda', 'negative'),
    ('Acordar cedo foi a pior merda q eu fiz hj', 'negative'),
    ('"Tal pessoa está interessada no evento" foi a pior merda que o facebook ja fez, deixa que todos CONFIRMEM PRESENÇA GZUIZ', 'negative'),
    ('Meu pai fez o favor de não me acordar, agora vou passar a merda do final de semana aqui', 'negative'),
    ('Velho e muito coisa é olheira , é trabalho , fotos , prova de vestibulinho , ir na casa de não sei quem ,colação , formatura puta merda', 'negative'),
    ('Aí meu deus! Que sensação horrível', 'negative'),
    ('RT @brubismallet: Não da pra nem sai p rua, ta horrível', 'negative'),
    ('Vai pela sombra pq merda seca no sol.[7323]', 'negative'),
    ('merda hoje eu faria um ano de namoro', 'negative'),
    ('Horrível quando você quer ver sua sobrinha mas tá de castigo', 'negative'),
    ('2015 foi um ano horrível', 'negative'),
    ('RT @loiradanielli: Homem que não sabe dar valor ao que tem, acaba sozinho, comendo piranha e fingindo que é feliz...', 'negative'),
    ('RT @jorginhoben10: eu nao acho ruim voce se gorda mas voce ocupa o luga de tres pessoa e sacanagem', 'negative'),
    ('É horrível se sentir sozinho, péssimo perceber que ninguém precisa de você...', 'negative'),
    ('Leo sem celular e horrível', 'negative'),
    ('Passei mal de madrugada, tive um sonho horrível', 'negative'),
    ('me acordar pra receber correspondência é muita sacanagem', 'negative'),
    ('Cara, 3x0 era um resultado injusto pra esse nosso primeiro tempo, time jogou fácil mas não mata o jogo, corremos riscos.', 'negative'), 
    ('Ficar sem sinal e sem internet é horrível ...', 'negative'),
    ('que dor de garganta horrível', 'negative'),
    ('RT @humdaora: "se ainda stalkeia é sinal que não superou" nada a ver, as vezes a gente stalkeia só p ver se a pessoa já ta tomando no cu, o…', 'negative'),
    ('Pleno sabado eu deveria estar transando e to aqui deitada no sofá esperando a morte vir me buscar', 'negative'),
    ('Amigo coxinha, #NãoParticipeDoGolpe pq qdo essa "modinha" acabar e vc perceber q ridículo foi, eu vou continuar rindo mt do mico q vc pagou.', 'negative'),
    ('@O_pereiratois Concordo! Acho ridículo essas atitudes, me faz pensar o quão mentiroso (a) uma pessoa pode ser ! Mas faz parte,"a fila anda"', 'negative'),
    ('A fulana chama chama a outra fulana de "piranha" queridaaaaa onde está o amor próprio?', 'negative'),
    ('2015 tem cada desenho novos ridículo da nem vontade de volta a ser criança', 'negative'),
    ('@elisa_sfr me desculpe me intrometer mas isso ta ridículo criticando o cara porque ele ta seguindo em frente e pior sao pessoas ja vividas', 'negative'),
    ('@Mellojapa_carol postou uma foto ridícula minha no tt', 'negative'),
    ('Garganta ruim..', 'negative'),
    ('Acordei com a garganta ruim, graças ao ar condicionado', 'negative'),
    ('RT @surtossurreais: Que morte horrível não conseguir dormir.', 'negative'),
    ('RT @FatosEx: vc tem cara de ser uma pessoa mt ruim fria e que vai acabar com minha vida ', 'negative'),
    ('RT @stwrtdalla: muito ruim quando vc ta de boa ai você pisca nao ta mais de boa ta ansiosa sua auto estima ta no chão e vc fica perdida sem…', 'negative'),
    ('A morte e a morte de Marília Pêra https://t.co/I49IieDwwn', 'negative'),
    ('Entrar no tt e levar porrada de spoiler de TO. Que morte horrível!', 'negative'),
    ('É a morte esse vestibular da uepg amanhã e segunda. ', 'negative'),
    ('Me enfio em cada fria que só por deus mesmo.', 'negative'),
    ('Fui cortar o cabelo e to ridícula', 'negative'),
    ('To bom não, aquela parada de ir no role e misturar cerveja da ruim!', 'negative'),
    ('Odeio awkward moments, é tão péssimo', 'negative'),
    ('Te perder de vista assim, é ruim demais', 'negative'),
    ('RT @stwrtdalla: muito ruim quando vc ta de boa ai você pisca nao ta mais de boa ta ansiosa sua auto estima ta no chão e vc fica perdida sem…', 'negative'),
    ('Como se fizesse diferença o que você acha ruim, como se eu tivesse prometido alguma coisa pra você.', 'negative'),
    ('Sou tão ruim com a Nicole que eu fico até com dó', 'negative'),
    ('RT @luancosta17: Tem que gente é tão ruim que mesmo tendo 2 caras, nenhuma presta.', 'negative'),
    ('Muito ruim pegar nojo de pessoas que você considerava', 'negative'),
    ('RT @vishdoidao: Você atingiu 100% do seu pacote de ridícula pfvr agora de um tempo', 'negative'),
    ('ruim dms atribuir uma música a uma pessoa', 'negative'),
    ('muito ruim isso de ter que pagar contas quem inventou essa besteira', 'negative'),
    ('RT @victoriaborri: vc dizia q eu era ruim e arranjou outro pior do q eu', 'negative'),
    ('Que clima ruim, pqp', 'negative'),
    ('Mais uma morte pós festa na USP! Até quando ? Antro...', 'negative'),
    ('Não sei porque diabos a letra do meu coisa tá ruim', 'negative'),
    ('@laraccsl caraca piranha falei que era pra estudar mais', 'negative'),
    ('Ai se sou eu, eu sou ruim!', 'negative'),
    ('Mor ruim esse travesseiro da nasa aqui mano', 'negative'),
    ('Meu twitter cismou de dar ruim logo hj', 'negative'),
    ('Pedi um drink muito ruim pqp', 'negative'),
    ('Lado ruim de usar óculos novo: antes eu não via as sujeirinhas no chão, agora eu vejo esse piso cheio de cabelos e pelo de gato...', 'negative'),
    ('RT @perpich157: Estou tão cansada, hoje eu vou sofrer viado...muita coisa pra resolver...E fazer, e mais os eventos da noite, cansativo...m…', 'negative'),
    ('RT @femininjask: TUDO ISSO é você exigir da pessoa uma atenção irrestrita pra que ela não seja culpada de "te fazer de trouxa"', 'negative'),
    ('So acho que sexta vou trabalhar muito cansado', 'negative'),
    ('Cara ficou MT feia a minha boca!! E ta doendo demais', 'negative'),
    ('RT @noss4gi: Não tem morte pior do que tirar 18388292 fotos e sair bem naquela em que não da pra ver seu rosto', 'negative'),
    ('muito ruim ler algumas coisas', 'negative'),
    ('RT @romanticotche: Quando eu pego o celular e não tem nenhuma mensagem me sinto abandonado numa ilha deserta sozinho DEIXADO A MORTE', 'negative'),
    ('Eu lembro até hoje de quem me deu parabéns e quem não me deu. Eu sou ruim, não dou parabéns p uma pessoa q não deu no meu', 'negative'),
    ('Por favor, evitem trocadilhos com meu sobrenome, tipo, você me Mattos de tesão. Sério. É muito ruim.', 'negative'),
    ('RT @inescarvalho55: É péssimo qnd n tens assunto c a pessoa q qrs falar', 'negative'),
    ('a única coisa ruim que aconteceu ontem foi que machuquei meu pé feio', 'negative'),
    ('O dia tá péssimo', 'negative'),
    ('Já acordo com noticia ruim tmnc td final de ano acontece alguma coisa...', 'negative'),
    ('Minha irmã tá vendo MTV e eu me pergunto como esse canal ficou tão ridículo de uns 10 anos pra cá', 'negative'),
    ('quem a vaness pensa que é pra alem de escutar musica do nbhd QUE ELA CHAMAVA DE RUIM e ainda colocar icon do canto', 'negative'),
    ('@cassiamenezz_ q feia essa xenofobia, vou te jogar nos grupos pra vc ser denunciada até perder o perfil', 'negative'),
    ('RT @bipolauren: O quão ridículo são aqueles caras que acreditam que o pinto deles é a divindade que desceu do céu e ficam ostentando o próp…', 'negative'),
    ('que porra hoje vai ter show do R5 e eu como sempre nao vou a vida e bastante desprazerosa muito ruim viver assim', 'negative'),
    ('Que dia horrível... Minha cunhada morreu na minha casa....', 'negative'),
    ('Minha irmã acaba com sua auto estima em uma frase e ela ta "só te ajudando" mas você fala uma palavra pra ela e você é a grossa, a ridícula', 'negative'),
    ('RT @ficantefalando: Tô cansado de vc me tratar assim', 'negative'),
    ('Não sei qual a doença de postar tudo no face, gente para que ta feio.', 'negative'),
    ('Dor nas costas ruim do crl', 'negative'),
    ('fala mal do meu aparelho como se fosse uma coisa ruim, pelo menos não esses dentes separados e escrotos', 'negative'),
    ('Péssimo atendimento no @applebees_poa. Ficamos 10 minutos sentados e nenhum garçom foi capaz de aparecer nem pra fazer o pedido de bebidas!', 'negative'),
    ('RT @aiaiai63: "puxa, tem uma notícia boa da gestão Haddad...vamo dá mas arruma um jeito de parecer ruim." https://t.co/CPUkp2ovdP', 'negative'),
    ('@felipeneto A mídia acabou com a Cultura. Agr nada relevante mais quem e Michel Teló comparado a Seu jorge. Pq Renato russo morreu cedo???', 'negative'),
    ('@MatheusMh11 Ele nem tem culpa do time jogar um futebol ridículo e ser eliminado na primeira fase da UCL não. Coisa da minha mente', 'negative'),
    ('RT @girlsimgs: amiga não é recalque de vc, é que realmente vc é ridícula desculpa a sinceridade', 'negative'),
    ('Lucas sempre com cara de cansado LucasLuccoNoCaldeirao', 'negative'),
    ('RT @neymarjr: Chateado, estou cansado de tudo !', 'negative'),
    ('Pelo menos o carinha q era otário se deu bem no final. Não posso dizer o mesmo da minha situação.', 'negative'),
    ('RT @lrvesgo: uai gente a pessoa pergunta se o fc ta bom e se falam que ta feio ela acha ruim, querida se n quer saber não pergunta', 'negative'),
    ('E essa gente forçando algo que não é, não existe algo mais ridículo do que isso', 'negative'),
    ('para q ta feio gabriela', 'negative'),
    ('RT @flashetero: não sei como vocês consegue gostar de scream queens é muito ruim', 'negative'),
    ('@avrilskins o ruim é q povo de humanas tem aquilo de fumar e beber demais, maconha, cerveja, etc.. E tem aquilo de poliamor.. N gosto disso', 'negative'),
    ('alguem avisa o lucas pra tirar esse bigode feio', 'negative'),
    ('RT @girlaws: meu cu chora toda vez que vejo blusinha sem estampa de uma cor só de paninho ruim 39 reais', 'negative'),
    ('@5HFarofa quase ligo pra minha mãe chorando, EU SOU UMA PÉSSIMA DONA MEU DEUS', 'negative'),
    ('sei como é ruim tu chorando atoa, e aquela pessoa tá sorrindo numa boa...', 'negative'),
    ('Sério que calor ridículo é esse', 'negative'),
    ('Gengibre é tão ruim', 'negative'),
    ('É tão ruim não ter dinheiro. OH vida de cão', 'negative'),
    ('Fica falando cada coisa ridícula', 'negative'),
    ('depois de lasanha, panetone é a comida mais ruim que existe', 'negative'),
    ('Bateu uma parada ruim agora', 'negative'),
    ('fiquei puta e vim embora, sacanagem', 'negative'),
    ('RT @bpldadepre: Se tá ruim pra você, torcedor red devil, imagine para aqueles times ricos que estão brigando na parte de baixo da tabela...…', 'negative'),
    ('@folha que coisa feia Folha!', 'negative'),
    ('RT @Itspedrito: hoje eu to mais cansada que a soma de todos os tweets da Luciana Gimenez com a palavra "exausta"', 'negative'),
    ('Fiquei um pouco otário faz-pouco-caso de tanto levar tapa nos ultimos anos. Desculpa por isso.', 'negative'),
    ('@redrumgiu @GabAugusto é fácil se você faz isso desde pirralha mas eu sou ruim demais', 'negative'),
    ('Depois de uma noite tão boa como ontem, um dia destes de merda a seguir é péssimo', 'negative'),
    ('Pegar trânsito num sábado pra voltar pra casa é sacanagem', 'negative'),
    ('RT @QenheVC: O ruim de ser irônico com gente burra é que se a pessoa não entende quem fica parecendo burro é você', 'negative'),
    ('@blogdojotace dois meses depois lançaram os exemplares! Eu besta comprei um usado confiando na palavra da Panini.', 'negative'),
    ('eu tô tão cansada de mim, da rotina, de todos, da vida', 'negative'),
    ('RT @FrasesDeRenato: Aí do nada você se distanciou e eu fiquei aqui perdido...', 'negative'),
    ('Briguei bem feio com a minha mãe essa semana, mano não tinha necessidade ela falar aquilo pra mim', 'negative'),
    ('RT @dissefalsiane: odeio quando eu digo q to cansado e alguém diz "cansado de que?" AMG EU NAO PRECISO TER UM MOTIVO, EU TO CANSADO E PONTO', 'negative'),
    ('Sem contar que o atendimento desse hospital da unimed é péssimo', 'negative'),
    ('RT @ShaiBrito: Eu demoro pra enxergar o lado ruim das pessoas, mas depois que eu enxergo, elas podem chorar sangue que não me convencem mai…', 'negative'),
    ('Cansada dessa bad', 'negative'),
    ('@Alexfeernandees fiquei boladona. Já chegou me acordando e achando que estava certa.. muito ruim esse negocio de irmã mais velha.', 'negative'),
    ('Acho q briguei com meu pai em um péssimo dia, q merdaaa', 'negative'),
    ('RT @BerthDurango: Quando vc passar na rua e ficarem te olhando.. .Nao se sinta o maximo..  Pois o feio e o ridiculo tbm chamam a atenção .', 'negative'),
    ('mt ruim ficar pensando em uma coisa q nem aconteceu mas q só de pensar já te deixa mal pra caralho', 'negative'),
    ('Pior coisa do ano foi ter perdido meu riocard PQP', 'negative'),
    ('RT @FTCuriosos: TODOS os alunos de uma escola no Texas se juntaram para consolar um colega, depois que a mãe dele morreu de Câncer. https:/…', 'negative'),
    ('esses artigos "não namore uma garota/um garoto que..." ou "namore uma garota/um garoto que..." gente, para que tá feio isso!', 'negative'),
    ('RT @twittandopravc_: Caráter feio estraga rostinho bonito, se liga.', 'negative'),
    ('RT @CHB_WestRap: Pq todo sábado é ruim?', 'negative'),
    ('irmao, pior de tudo eh eu querer usar o wpp e só poder usar ele no computador... e o notbook estar estragado!!! ta certim', 'negative'),
    ('Acabei de jogar a pior partida da minha vida no @Battlefield', 'negative'),
    ('RT @IsadoraLunar: O @twitter no Windows Phone é a pior coisa que existe, e eu que uso o Twitter praticamente o dia inteiro acabo me ferrand…', 'negative'),
    ('RT @Cruzoeiro: Na boa, é sério isso aqui? Atleticano tem uma doença pior que câncer na boa. https://t.co/kzjUv9udFW', 'negative'),
    ('lembrei que eu dei uma volta nos amigos do x tudo del márcio ontém e tô péssima viu', 'negative'),
    ('pedi um coque like vitoria does mas ela disse q ia ficar feio e prendeu o meu cabelo todo p um lado so??? tipo AF', 'negative'),
    ('Ela assim, "outros"  pessoas, eu aqui... Noite ruim.', 'negative'),
    ('RT @LennonBossa_: NÃO TEM COISA PIOR DO QUE FICAR LONGE DE QUEM A GENTE AMA', 'negative'),
    ('odeio quando minha mãe sai e n atende o telefone, fico perdida em casa sozinha', 'negative'),
    ('RT @_mareanas: FAST AÇAÍ É MUITO RUIM', 'negative'),
    ('A cada dia é um dia pior aqui em casa.', 'negative'),
    ('RT @thamitirando: é bem ruim quando vc tá confiante numa coisa e PLAU', 'negative'),
    ('RT @_eujohn7: pior sábado!!!', 'negative'),
    ('@taehospicio so musica ruim pqp', 'negative'),
    ('RT @PastorMalafaia: Vamos orar pelo Brasil , a coisa está feia, um desgoverno, uma incompetência total.Quem paga o pato é o povo.Fora Dilma…', 'negative'),
    ('@arrobadebo miga seu crush raspou a cabeça tá mt feio', 'negative'),
    ('Lado ruim da cirurgia: passar mais de 2 meses sem tocar violão :(', 'negative'),
    ('RT @OpsGrazi_: Timidez e a pior merda pra vc pode ter', 'negative'),
    ('@pxcifyhim Se você for comprar aqureles cliker cuidado pra não comprar pequeno igual a anta aqui mt ruim doe pfa crl', 'negative'),
    ('Acordei agr, e vi que ta chovendo, esse tempo ta de sacanagem', 'negative'),
    ('Tem muita coisa ruim sendo compartilhada.', 'negative'),
    ('RT @amandamoura78: Deus que me perdoe, mas sinto muita raiva dessas paradas..o pior e ver essas garotas rindo', 'negative'),
    ('Otro fin de semana perdido.', 'negative'),
    ('Deus me dê muita força. Cheguei no meu limite mesmo. Se acontecer algo mais de ruim, sinceramente, não irei suportar.', 'negative'),
    ('Mas você é besta mesmo neh', 'negative'),
    ('Se você quer, chega junto, não fica em cima do muro com orgulho besta, p merda', 'negative'),
    ('Rolando karaokê especial Reginaldo Rossi no salão do meu prédio, mas parece q tão cantando dentro da minha casa ou pior no meu quarto.', 'negative'),
    ('RT @Larissa23256014: Só falta acabar a energia pra ficar pior.', 'negative'),
    ('Mt ruim sair de casa sozinha, medo da porra de pegar trem essa hora e descer naquela estação horrivel do meier', 'negative'),
    ('teve um show de fogos aqui agora que minha cachorra só quase morreu', 'negative'),
    ('essa fanfic além de ser ruim ainda tem parte 2 COMO PODE', 'negative'),
    ('Minha tosse tá pior que a minha vó fumante, meu peito dói, minha cabeça dói e tô com febre pra piorar tudo .-.', 'negative'),
    ('O universo foi mesmo injusto com a tiffany', 'negative'),
    ('RT @RecitouOriente: Aquele momento em que você percebe que não sente mais necessidade de falar com a pessoa como antes, que alguma coisa al…', 'negative'),
    ('se sentindo péssimo', 'negative'),
    ('RT @namorei: chorar quando vc ta com raiva é a pior coisa que existe porque vc tenta agir de uma forma seca e indiferente mas acaba chorando', 'negative'),
    ('@lopessjuuh aldo perdeu feio pra caralho', 'negative'),
    ('Fui dormir depre e acordei pior', 'negative'),
    ('Eu preferia não ter ido a festa. Deu ruim :(', 'negative'),
    ('To ruim, q ressacao... Nem da cama levantei ainda', 'negative'),
    ('RT @salvebia_: Pior raça é ex querendo mostrar que superou a pessoa', 'negative'),
    ('Sabe, 2015 ta sendo um péssimo ano', 'negative'),
    ('São 14h ainda e eu querendo que o dia acabe rápido. Domingo é de longe o pior dia da semana. Haja filme e série.', 'negative'),
    ('Pior coisa é tomar culpa por algo que você não fez', 'negative'),
    ('Romero ganhou msm assim? Ah q lixo! Só com a trava q o jacaré deu nele já era p ter perdido mane', 'negative'),
    ('Minha mãe tem o dom de ser desagradável', 'negative'),
    ('sou uma péssima mãe', 'negative'),
    ('RT @CiteiFrasees_: 2015 foi uma merda muito significativa .. Começou da melhor forma, e ta terminando da pior.', 'negative'),
    ('Ta mttt ruim a minha tela ta TODA rachada', 'negative'),
    ('nossa eu adoro a maria de coração,mais quando ela escreve socorro e pior ainda é o que ela escreve errado ela fala errado,por isso me irrito', 'negative'),
    ('a semana passada foi a pior semana de todas, espero que esta seja melhor', 'negative'),
    ('Pq a internet tem q ser tão ruim no meu quarto???', 'negative'),
    ('Meu humor ta péssimo', 'negative'),
    ('Tô todo colorido mano, cai mo feio ontem', 'negative'),
    ('Parte ruim pós night: cheiro ruim no cabelo', 'negative'),
    ('Bateu a BAD Aqui Em Saber Que Não To Na Festa De 3MVS', 'negative'),
    ('RT @Seifiane: tirar foto com copo de cerveja no banheiro não é bonito nem descolado é nojento', 'negative'),
    ('RT @SouPositividade: É triste ver uma amizade acabando aos poucos...', 'negative'),
    ('sem paciência pra gente que escreve "anciedade" "anciosa"..', 'negative'),
    ('RT @bugalizado: Paciência é tudo. Tudo o que eu não tenho.', 'negative'),
    ('não tenho paciência para fazer exercicios', 'negative'),
    ('Saudade bate q dói', 'negative'),
    ('Oi @profeborto! Sem paciência eu! Tem coisas que é difícil entender né?', 'negative'),
    ('ter esperança é um erro.', 'negative'),
    ('é muito vacilo p pouca paciência', 'negative'),
    ('Hj a primeira coisa q chegou ao fim foi minha paciência', 'negative'),
    ('RT @ModestoGeovana: A festa estava massa, tirando a parte de que o menino que me deu carona enfiou o carro em cima de uma pedra lá no sítio…', 'negative'),
    ('Pessoas que não conhecem o amor, o respeito e a boa vontade vão morrer sozinhos, pq chega uma hora que nem a família mais aguenta', 'negative'),
    ('RT @mdsjennys: ás vezes eu acho que a meia idade chegou pra mim mais cedo pq não consigo ver graça nesse tipo de festa q todo mundo vai', 'negative'),
    ('Não da pra ter paciência com a zaga. Os caras são ruins ate no FIFA vei', 'negative'),
    ('n entendo como as pessoas vao p uma festa p brigar meu deus fica em casa na moral', 'negative'),
    ('Em Brasília, organizadora reclama do baixo número de manifestantes https://t.co/vBlekok1PX', 'negative'),
    ('Penssndo seriamente em desistir da festa do show time', 'negative'),
    ('@yasfiorelo @Gramonster Com td respeito pra quem gosta.Q merda !!!!!', 'negative'),
    ('alguém que ache grosseiro e nojento siall pode falar comigo? preciso compartilhar o nojo', 'negative'),
    ('Não tenho paciência p gente folgada', 'negative'),
    ('@bbllamyblake você não merece o meu respeito', 'negative'),
    ('Hoje é um daqueles dias que to sem paciência pra gente burra, também conhecido como mais um dia comum', 'negative'),
    ('Cerveja quente é a pior coisa que existe no mundo', 'negative'),
    ('RT @maristelice: agora aqui chegou um momento que eu não to sentindo nada nem felicidade nem tristeza nem nada eu acho que se chama tédio', 'negative'),
    ('Não sei qual é o limite das pessoas, criar um grupo sobre "Homicídios Pelotas" pra compartilhar fotos das vitimas. Pelo amor de Deus!!!!!!!!', 'negative'),
    ('O Meu dia quando começa dando errado é foda. Não para. Sempre um 7x1. Muita força e paciência p/ poder curtir o resto dele.', 'negative'),
    ('RT @takeforlovingio: Viu nosso esforço e ainda disse que ia tentar ir e recompensar isso, eu to ficando bem triste', 'negative'),
    ('Bloqueio logo p parar de encher a paciência', 'negative'),
    ('RT @easytobreaks: cansada desses negocios de youtube desse povo fazendo sucesso com nada desses videos sem graça bora extinguir', 'negative'),
    ('@liarsomebody cabô amizade, vo ti brokiar', 'negative'),
    ('com todo respeito não consigo gostar da anitta gente', 'negative'),
    ('Anitta e Claudia leite no mesmo metro quadrado. Senhor, haja paciência pra tamanha chatice', 'negative'),
    ('@cindymaraia aff gente q horror, sou CS mas tem uns q são hipócritas querem respeito mas n respeitam credo', 'negative'),
    ('como pode uma foto acabar com todo sua felicidade', 'negative'),
    ('RT @Bruh_DoLucco: Olha essas fãs do Luan ñ tem respeito nenhum, espero q lembrem q td q a gente planta a gente colhe, e é aqui msm. O futur…', 'negative'),
    ('RT @LembrandoAmor: A palavra "amizade" já teve mais valor..', 'negative'),
    ('Só têm idade mesmo, porque maturidade não têm nenhum pouco!', 'negative'),
    ('@laraasias nao sei se da pra manter a nossa amizade dps desse tuite', 'negative'),
    ('RT @JulioCarmona_: A @cristilobo acaba de dizer na @GloboNews q as MINI-festações de hj fracassaram por causa da proximidade do natal. Tá b…', 'negative'),
    ('@lovemelikelolo eu n sou obrigada a ler essas coisas, vai la cantar p ela e me deixe em paz', 'negative'),
    ('@acpppppprovesi não esquenta a cabeça,deixa esse povô se fode.eles tão preocupado com as festa de final de ano eo carnaval qjá está chegando', 'negative'),
    ('RT @blackislife3: só espero é que amanhã ninguém me lixe a cabeça, n tenho paciência', 'negative'),
    ('RT @noitesombria: Confundi saúde com saudade e agora não paro mais de chorar.', 'negative'),
    ('RT @jul14rique: baboooou a festa dia 17,af', 'negative'),
    ('Tá tenso festa na rua,  mas não curto nada que tenha nesse lugar  "-"', 'negative'),
    ('RT @Jess_barbie_21: Não tenho paciência para tanto drama', 'negative'),
    ('la vem achando que só americano presta e faz sucesso puta que pariu cansei de tentar tirar preconceito e ignorancia dos @s nao da certo', 'negative'),
    ('RT @ccsilvaff: eu não tenho paciência p falar com alguém que não seja mt importante p mim por sms', 'negative'),
    ('Passou vergonha na festa cm aquela maquiagem, certezaa', 'negative'),
    ('Provei cerveja com energetico... HORRIVEL, continuo nao gostando de cerveja.', 'negative'),
    ('aquele palhaço q me poupe a falta de maturidade pq se eu me passo é a sério', 'negative'),
    ('RT @soutosco: mto troxa essas pessoa q AVISA q vai dar unfollow ne… é tipo avisar pra td mundo q vc ta indo embora de uma festa q ngm nem l…', 'negative'),
    ('RT Parte do palco montado para festa de aniversário da cidade desabou. Várias árvores foram derrubadas com a intensidade dos ventos.', 'negative'),
    ('RT @blurryfacz: algm avisa p youtube tirar essa propaganda da tim eu n aguento mais só kero assistir sweater weather em paz WATCH SWEATER W…', 'negative'),
    ('RT @eusomerhalder: odeio quando espirro e ninguém diz saúde', 'negative'),
    ('Parem de mandar mensagens a dzr q n tou bem... Fdc eu sei crl deixem me em paz', 'negative'),
    ('Quando parece estar tudo perfeito, tudo na paz, sempre tem um pra estragar com tudo', 'negative'),
    ('RT @OnceLucasLucco: Criaram uma merda de uma rivalidade onde só existe amizade enquanto tão na imaturidade de suas ignorâncias eles tão zua…', 'negative'),
    ('deviam-me dar mt dinheiro por eu ter tanta paciência por aturar os meus professores irritantes desde de manhã', 'negative'),
    ('algumas pessoas deveriam aprender o que é limite, respeito é bom e todo mundo gosta', 'negative'),
    ('Como alguém tem coragem de roubar da saúde plmdd', 'negative'),
    ('se eu não tenho paciência nem com meu irmão vc acha que eu vou ter com você', 'negative'),
    ('RT @pqplolads: Deixo bué de responder às pessoas mas juro que não é por mal, às vezes é mesmo falta de paciência', 'negative'),
    ('é p tirar o restinho de paciência que eu tenho', 'negative'),
    ('RT @gabsafernandes: uma amizade baseada em interesse', 'negative'),
    ('RT @OnceLucasLucco: Já existiu respeito aqui nesse site , pois é ... As pessoas tem mania de querer chamar a atenção querendo diminuir os o…', 'negative'),
    ('tenho paciência limitada para mood swingers', 'negative'),
    ('RT @anadoratomazz: não lembro nem a ultima festa que eu fui.. que fase', 'negative'),
    ('RT @luacardosod: N tenho paciência com gente q a gente tenta ser gente boa, fazer amizade e tal ai a pessoa ja acha que vc quer pegar ela e…', 'negative'),
    ('Minha mão ralou por conta do touro mecânico na festa', 'negative'),
    ('Cerveja ruim da preula', 'negative'),
    ('Mano, eu to me segurando p não vazar uns print, tão brincando com a pouca paciência q eu tenho!', 'negative'),
    ('Traição na amizade dói tanto cm numa relação', 'negative'),
    ('RT @RecitouOriente: Acho que felicidade é só para alguns.', 'negative'),
    ('RT @RBfortinho: Meu mal é criar muita expectativa.', 'negative'),
    ('Na dúvida, escolha o silêncio. Ele incomoda, irrita, chateia, não gasta sua energia, e ainda por cima, preserva a tua imagem.', 'negative'),
    ('A pessoa não responde a vtnc', 'negative'),
    ('Já tô me preparando pra cortar a fita da amizade', 'negative'),
    ('RT @piscianux: criar expectativa e não acontecer nd do esperado mais um dia normal', 'negative'),
    ('Estava hoje na expectativa de tomar um açaí c morango do Beto e tava fechado', 'negative'),
    ('Ignorando textao politico idiota no Facebook para manter a amizade. Acho que amadureci meu irmao kkkj https://t.co/lb5rQ3T3SB', 'negative'),
    ('Até latada de cerveja na cabeça eu tomei...', 'negative'),
    ('A corrupção subtrai educação saúde cultura desenvolvimento Não queremos mais um Governo q subtrai nossas perspectivas A democracia empodera', 'negative'),
    ('De amizade assim eu tô foraaaaaaa', 'negative'),
    ('Todo esforço jogado no lixo!', 'negative'),
    ('mano minha mãe n me deixa em paz q inferno', 'negative'),
    ('RT @ilaislaassuncao: o dia que eu não tomar no cu eu faço uma festa', 'negative'),
    ('@amplaenergia #faltadeluz Estou sem luz há mais de 16hs total falta de respeito com o cliente. Ação já pronta para entrar na justiça.', 'negative'),
    ('Esperar alguma coisa de vc é o mesmo que jogar um cachorro de um prédio na esperança de que ele voe', 'negative'),
    ('RT @esseteucu: vc ja tá com a saúde mental uma bosta dai vem uma pessoa olha e opa sera que da pra piorar? hmm vou dar uma força', 'negative'),
    ('Municípios em crise: União admite que não conseguirá repassar verba da Saúde https://t.co/BAGpT155U8', 'negative'),
    ('RT @atereziha: vai lavar umas louças deixa os gays em paz!!!!!!', 'negative'),
    ('RT @fifthstylinsow: @amosoularry eu nao mereço nem uma amizade, eu sempre estrago tudo', 'negative'),
    ('Eu so quero que chegue logo a noite, pros meus pais irem dormir e eu poder chorar em paz', 'negative'),
    ('Quadrilha é acusada de desviar milhões da saúde pública no RJ https://t.co/6LpUPNTHOB', 'negative'),
    ('Ser excluída é tão ruim, mas depois de um tempo você se acostuma', 'negative'),
    ('Ruim de estar em um grupo de garotas é q elas falam de signos e de signos eu n ENTENDO NADA', 'negative'),
    ('"Se é ruim Leticia" tenho q ouvir isso umas trezentas vezes por dia', 'negative'),
    ('RT @Expressagem: O nosso pior inimigo é a própria mente.', 'negative'),
    ('Tem gente que muda é ao invés de mudar pra melhor muda pra pior', 'negative'),
    ('RT @untiltheend1Dts: E eu pensava que com a saída do Zayn 2015 já podia ser considerado o pior ano. Mas ainda tinha mais. (+) #MTVStars One…', 'negative'),
    ('minha mãe queria me levar pro mc, mas to péssima do estômago.', 'negative'),
    ('RT @yrtunc: Gente ingrata é a pior raça', 'negative'),
    ('RT @JonnyPinho: Deve ser mt ruim perder um amigo :(', 'negative'),
    ('@089Tae FEIA SEU CU', 'negative'),
    ('Se tem uma raça que eu tenho realmente preconceito essa raça é o lambe-botas. O lambe-botas é tudo o que há de pior na humanidade', 'negative'),
    ('Ela é muito linda para namorar um cara tão feio.', 'negative'),
    ('RT @vitoriaroucha: e essa minha mania feia de priorizar quem não da a mínima pra mim', 'negative'),
    ('RT @FrasesDeRenato: Não sei o que está pior, essa tristeza no seu olhar ou esse sorriso disfarçado.', 'negative'),
    ('Muito ruim perder um amigão, sei bem como é isso... Penso logo no PVZÃO!!', 'negative'),
    ('Mano, odeio ver esse monte de notícia ruim sobre o spfc', 'negative'),
    ('Elástico de aparelho é a pior coisa, tnc', 'negative'),
    ('RT @mari_Amapa: Parece que hoje deu ruim. É coice pra todo lado.', 'negative'),
    ('Queria ir ao cinema, no entanto porém contudo só tem filme ruim', 'negative'),
    ('Como é ruim ver amigos sofrer ne bicho', 'negative'),
    ('RT @desamei: aquela vontade de chegar na pessoa, dar um tapinha no ombro e falar: para que tá feio', 'negative'),
    ('Eu odeio lavar louça, pior coisa', 'negative'),
    ('RT @ttwitandu: Ai a pessoa tem covinha e se acha feia', 'negative'),
    ('@PaiTroll_ Pior que eu bati o olho e achei que era o Charlie Sheen, uma pena que não da pra desejar aids pra quem joga Minecraft.', 'negative'),
    ('@helikedrew pior que é verdade, meu ela é muito ridícula eu não me conformo, cada dia pior', 'negative'),
    ('RT @antigapaz: Pegar nojo de alguém é pior do que ódio.', 'negative'),
    ('fã que se acha sabe tudo: pior tipo', 'negative'),
    ('Homem morre ao cair de escadas rolantes: Um homem, de 54 anos, morreu depois de cair de umas escadas rolantes ... https://t.co/wjOAgmmHyu', 'negative'),
    ('Ainda não sei o q é pior: correr ou matemática', 'negative'),
    ('Meu dia ta sendo pior do que a noite.', 'negative'),
    ('Cara o negócio com gosto ruim,da vontade de vomitar', 'negative'),
    ('RT @Amizade: Minha mãe tinha razão, crescer é ruim pra caramba!', 'negative'),
    ('@takemetosk eu tive um hamster que perdeu um olho e morreu, e tinha duas cachorras que tive que dar pra mudar pro apartamento', 'negative'),
    ('Isso de dormir mt é tri ruim, qlqr lugar q eu fico parada já pego no sono', 'negative'),
    ('Essa geração ta terrível , não sabe nem oque é brincar de boneca , agora pergunta de beijo na boca pra vê se não sabem k k to boba aqui', 'negative'),
    ('Como que é ruim não ter seu próprio dinheiro', 'negative'),
    ('Ai cara, é ruim demais ter peitos grandes', 'negative'),
    ('RT @dumdc_: porque que menina fuma ? acho tão feio', 'negative'),
    ('É mt ruim trabalhar a tarde ..', 'negative'),
    ('Acho o governo  Dilma pessimo  https://t.co/ITrDPKl64H', 'negative'),
    ('Notícia péssima pro time, Byron Maxwell perdeu outro treino.', 'negative'),
    ('RT @pqpezzini: tudo de ruim tá a minha volta e tudo que eu quero tá a quilômetros de distancia de mim', 'negative'),
    ('a garota já é feia e ainda tira ft fazendo careta haha mano n para vai ser zuada', 'negative'),
    ('@_MarcosQueiroz_ menino, ouvi dizer que o Artur (que era casado com o Bruno) morreu.', 'negative'),
    ('3G é ruim dms !', 'negative'),
    ('Tomei uma vodca ontem com suco que parecia o maracujá joinville de tão ruim', 'negative'),
    ('Nunca tive vergonha de assumir os meus erros, agora nego querendo fuder minha vida com coisa que nem é verdade? Para q tá feio, tá ridículo', 'negative'),
    ('Ministro diz que país tem perdido batalha contra mosquito da dengue https://t.co/tdO9ZMCkXb', 'negative'),
    ('esse album da willow eh tao ruim q sinto vontade de chorar so de pensar', 'negative'),
    ('Por que a @_AntoniaLuiza não me avisou que o novo Jogos Vorazes é uma titica, não teria perdido 4 hs com aquilo!', 'negative'),
    ('era só o que faltava o carregador começar a ficar ruim', 'negative'),
    ('RT @EuFaIando: A vida real ta faltando um "Desfazer amizade"', 'negative'),
    ('Muito ruim você ficar impossibilitado de fazer algo por causa da sua saúde', 'negative'),
    ('essa vida ta mo bosta preciso compartilhar', 'negative'),
    ('as vezes eu vejo uma coisa e fico com uma vontade absurda de problematizar mas não problematizo pq já é dificil fazer amizade', 'negative'),
    ('Onde falta respeito... A amizade vai pra o lixo...', 'negative'),
    ('RT @Agarie: Enfim, se alguém procura um plano de saúde para idosos, recomendo em hesitar a Prevent Senior', 'negative'),
    ('Ainda menor que o Zika vírus é a estatura moral de quem malbaratou recursos que garantiriam #saúde em lugar de tantos bebês c/microcefalia', 'negative'),
    ('RT @RadiodoMoreno: Exclusivo: Em dura resposta, Temer chama Renan de coronel e exige respeito à memória de Ulysses, citado pelo senador na …', 'negative'),
    ('RT @umbjpvcs: um minuto de silêncio por todas as crianças que não veem a hora de virarem adolescentes pq acham que a adolescência é a melho…', 'negative'),
    ('@enrcqueiroz Umas tem pai ciumento. Outras irmãos. E eu tenho você, psicopata que não me deixa viver em paz.', 'negative'),
    ('blz pessoal todo mundo ja viu a foto daquele cara acendendo um cigarro de maconha com o filtro do star wars ja pode parar de compartilhar', 'negative'),
    ('RT @saltxchrisb: é tudo uma questão de FALTA DE RESPEITO COM O TRABALHO DO ÍDOLO! AnywayOnVevo', 'negative'),
    ('@benzoceans mais respeito comigo pq vc não tá falando com qualquer uma não', 'negative'),
    ('@TuaMenezesC1R  será que dá pra vc deixar o meu irmão e isabela em paz??', 'negative'),
    ('RT @SintoniaVerso: Meu respeito acaba quando sua ignorância começa.', 'negative'),
    ('RT @luanlovato: triste pois vo te que cancela minha festa de aniversário agora https://t.co/tyhlQTc0KT', 'negative'),
    ('Um chá antes de deitar para ver se consigo descansar em paz. Queria não dormir e acordar pensando em problemas.', 'negative'),
    ('@anabheatrys_ inventei historia falando que minha vó ia vir so pra ficar e nao vai ter mais festa morre porra nmrl', 'negative'),
    ('fala de falsidade mas é a primeira a criar amizade por status e por foto legal no instagram', 'negative'),
    ('De manhã foi bue fixe mas essa p*** estragou a minha felicidade toda -.-', 'negative'),
    ('RT @Expressou: Eu nem puxo mais assunto, mesmo que o teu silêncio me machuque. Prefiro assim, não corro o risco de ser ignorado.', 'negative'),
    ('Aquele momento que tu fala que tem preconceito das festa em Guaíba e tu já sente os xingo vindo.', 'negative'),
    ('RT @bitterabbit: a cada dia um grande esforço pra não fazer barraco', 'negative'),
    ('RT @Nefazodona: não acredito a juana fez meme com minha ex namorada que falta de respeito com a juliana', 'negative'),
    ('mãe se vc não quer falar cmg não vida real não venha me mandar mensagem de achar a felicidade no wpp', 'negative'),
    ('OPERADORAS DE BOSTA!!! Egotistas do caramba, não sabem aproveitar o sucesso de um aplicativo', 'negative'),
    ('TÃO difícil arrumar uma amizade verdadeira', 'negative'),
    ('Cara, nao suporto qnd chegam comigo em tom de fofoca """nossa, quase certeza que fulano é gay""". E DAÍ??? DEIXA O FULANO SER GAY EM PAZ', 'negative'),
    ('Queria compartilhar todas minhas foto mas eu esqueço que ninguém liga', 'negative'),
    ('RT @HaikaissVersos: Cuidado com o que cê faz, destino é capaz de tirar sua paz, ele não gosta de avisar.', 'negative'),
    ('nenhuma amizade me decepcionou tanto quanto a do tony; às vezes parece até mentira que brigamos', 'negative'),
    ('RT @pabNonato: As críticas só aparecerem qdo o sucesso incomoda', 'negative')
]
