negative_tweets = \
[
    ('RT @raahandradee: Você não merece 1% do amor que eu te dei', 'negative'),
    ('RT @andradeffc: vasco fluminense e botafogo interessados no hernane ai vcs n sabem pq o futebol carioca ta esse lixo', 'negative'),
    ('A maquiagem ja vai ter virado uma bosta quando chegar na festa', 'negative'),
    ('Quanta gente chata, pelo amor de Deus!', 'negative'),
    ('Uma falta de respeito tremenda com o espaço alheio https://t.co/w0JJzZuuZ3', 'negative'),
    ('RT @falsianecobra: Dai a mina posta " odeio menina puta "  .. Fofa cade o amor próprio ?', 'negative'),
    ('É tão ruim saber, que vou pra alguma festa, lugar, você não está mais ali, pra dar opinião sobre a roupa, etc', 'negative'),
    ('@Alessandralombl agora você não tem motivos pra ter amizade com aquela lá', 'negative'),
    ('pelo amor de Deus quero q esse ano acabe logo', 'negative'),
    ('não existe amor em sp', 'negative'),
    ('RT @CaioFAbreuCitou: Não suporto meios termos. Por isso, não me doo pela metade. Não sou sua meio amiga nem seu quase amor. Ou sou tudo ou …', 'negative'),
    ('Paciência tem limite', 'negative'),
    ('Mas PORRA FALAR QUE PRA TER SUCESSO TEM QUE SER BONITO É A MAIOR MERDA QUE EU JA OUVI', 'negative'),
    ('RT @Privacidades: Nunca fui de implorar amizade. Quer ficar? Fique. Não quer? Foda-se. Mas se for para ficar, fique porque quer, não por ob…', 'negative'),
    ('Deus me dê paciência com os cancerianos da vida', 'negative'),
    ('Eu vejo que o amor é uma merda porque um bebe quando nasce já chora', 'negative'),
    ('RT @daranavy: eu digo q não gosto que façam uma merda e continuam a fazer fds santa paciência', 'negative'),
    ('RT @mariolobato: Alerta! Estamos a beira do maior retrocesso na história da Saúde Mental brasileira! https://t.co/LWITJnJN2c', 'negative'),
    ('Falta amor, falta compreensão, falta humanidade, falta Deus! E se falta Deus, falta tudo.', 'negative'),
    ('Você não era príncipe , era sapo me enganei com Marcinho kalatimbu esqueça você amor', 'negative'),
    ('mas vou me manter distante, porque não quero continuar "amizade" com a maoiria', 'negative'),
    ('Daí-me paciência com esse menino, viu?! Pqp.', 'negative'),
    ('Viado quer respeito mas... Mas o que seu idiota? E eu tendo que fazer a linha didática..', 'negative'),
    ('comprei um tênis novo, jurei amor eterno mas ele resolve que vai foder com meu calcanhar todinho', 'negative'),
    ('Eu não  respeito quem esconde. Ficar fazendo propaganda ingmorante do PT, só pode se um  dos corruptos.Então,dê-se ao respeito e cala boca!!', 'negative'),
    ('RT @naosejatrouxa: era um vez minha paciência e ela acabou, fim', 'negative'),
    ('sem essa de "é pra sempre" é amor até deixar de ser', 'negative'),
    ('RT @UOLNoticias: Acordar tarde nos fins de semana pode prejudicar sua saúde https://t.co/g67NkKr0xe', 'negative'),
    ('@olIgmagcon ah sim, eu acho essa coisa de ter crush chata e nao sinto amor por ninguem', 'negative'),
    ('RT @httpsignos: Gêmeos no amor um dia te ama e no outro te acha um F.D.P.', 'negative'),
    ('Essa gripe da amizade que surgiu do nada acabou com meus planos de hoje :(', 'negative'),
    ('RT @Eusemprelindo: Não tenho sorte no amor', 'negative'),
    ('RT @warrlly: fico imaginando eu criar minha filha com todo amor e carinho ela cresce e vira fã de felipe neto', 'negative'),
    ('ODEIO PESSOA CHICLETES E SEM PACIÊNCIA', 'negative'),
    ('Agr é um p cada lado, e o silêncio fala mas parecemos dois rivais', 'negative'),
    ('Olha p mim e me diz se alguma vez eu te deixei faltar amor..', 'negative'),
    ('RT @Renata_lopes22: Olha o que você fez, era o meu grande amor e hoje é só mais um ex', 'negative'),
    ('Mereço gente preconceituosa chorando no inbox pq desfiz amizade falando que "eu nao sei lidar com ~opiniões diferentes~"', 'negative'),
    ('Rola umas cantadas bem escrotas e eu n tenho paciência', 'negative'),
    ('RT @nacaodepre: Primeiro dispensado do Vasco foi o respeito', 'negative'),
    ('RT @arturdotcom: O bicho homem hetero tem vergonha de dizer "te amo" pra namorada e faz textão sobre sua paixão por um jogador de futebol.', 'negative'),
    ('Minha paciência ta ó', 'negative'),
    ('RT @explicandoindie: here - alessia cara eu sou uma pessimista antissocial e to pouco me fudendo pra essa festa na verdade se eu pudesse es…', 'negative'),
    ('RT @maah_romao: não tenho paciência nem para mim mesmo imagina para você', 'negative'),
    ('Aborrecendo por não poder nem bater um papinho, tomar uma cerveja, distrair...', 'negative'),
    ('@PriscilaSilva_2 muito chato tenho paciência mais não', 'negative'),
    ('preciso arruma um role p amanha.. N quero ir naqela festa, por conta daqla menina', 'negative'),
    ('Que merda fui fazer da minha vida maldito o dia q eu quis ir naquela festa', 'negative'),
    ('RT @inspirou: A minha felicidade te incomoda? Engraçado, a tua nem me interessa!', 'negative'),
    ('RT @Oliviapallito_: Gente que fica de um lado resmungando até você perde a paciência e explodir', 'negative'),
    ('Morre médico espancado em festa na USP: Segundo a universidade, serão aplicadas sanções administrativas aos or... https://t.co/V7NaMflvxM', 'negative'),
    ('Amizade é como cordas de violão, elas se quebram e podem ser remendadas, mas nunca terão novamente o mesmo som.[8867]', 'negative'),
    ('RT @stylesonthewind: "o shawn ta separando camren" vcs mesmas destruiram a amizade das duas,parem pfvr Shawn e Camila', 'negative'),
    ('RT @VoceNaoSabiaQ: O ciumento passa a vida tentando descobrir o segredo que irá destruir a sua felicidade.', 'negative'),
    ('Ao ver a foto de FHC sentado no trono golpista lembrei que Jorge Rafael Videla morreu naquela posição. https://t.co/ywMwCwhZR2', 'negative'),
    ('@Abbadon_nado eu to sem esperança tbm mas so vou saber se vou ou nao quando tiver confirmada. até la vamos nos preparar', 'negative'),
    ('@biavalente5 foi bom tu ter perdido a festa mana, foi o ò', 'negative'),
    ('Antes um recado:Tenho muita paciência mas tá por um fio #direta https://t.co/THgUWIgwwb', 'negative'),
    ('RT @noitesombria: Expectativa boa é expectativa morta.', 'negative'),
    ('RT @VoceNaoSabiaQ: Psicologicamente, depois de ser decepcionado tantas vezes, você começa a perder a esperança em tudo.', 'negative'),
    ('RT @baduum_tzz: não há namoro ou amizade alguma q dê maior desilusão que num fim de semana acordares cedo devido à puta da rotina da escola.', 'negative'),
    ('Não tenho paciência pra ter muitos grupos no whatsapp', 'negative'),
    ('RT @saulo_silvaa: Mina que fica c td mundo pra mim não tem respeito na favela', 'negative'),
    ('Não tenho paciência p esse tipo de gente, vai se fuder p lá', 'negative'),
    ('Quando surge uma esperança de melhora... Um avalanche de coisa ruim.', 'negative'),
    ('Sempre tem um pra testa sua paciência', 'negative'),
    ('RT @B00ubazar: Não sei do que fujo, a esperança pouca me resta', 'negative'),
    ('É triste ser tão novo e já achar que a vida não presta bem que alguem podia me ligar e me convidar p uma festa', 'negative'),
    ('@cissamalan Sabe de muita coisa ao meu respeito me hackeou foi ?e eu ligo pra essa sua besteira mimadinha', 'negative'),
    ('RT @g1: Noivo que comprava maconha antes de casamento é preso e perde festa https://t.co/ESd7ocGn4O https://t.co/vvRmpX5kgN', 'negative'),
    ('RT @fabio_freitas50: A felicidade de uns incomoda outros', 'negative'),
    ('Não tenho paciência para quem se faz de coitadinho.', 'negative'),
    ('RT @rwvivalarry: Harmonizer: "odeio o Shawn"', 'negative'),
    ('@ENZlNHODO15 eu tava na casa dum amigo meu, fui dormir as 7 acordei as 10, mó merda', 'negative'),
    ('não gosto de gente que fica babando ovo de gente merda', 'negative'),
    ('Acordar cedo foi a pior merda q eu fiz hj', 'negative'),
    ('"Tal pessoa está interessada no evento" foi a pior merda que o facebook ja fez, deixa que todos CONFIRMEM PRESENÇA GZUIZ', 'negative'),
    ('Meu pai fez o favor de não me acordar, agora vou passar a merda do final de semana aqui', 'negative'),
    ('Velho e muito coisa é olheira , é trabalho , fotos , prova de vestibulinho , ir na casa de não sei quem ,colação , formatura puta merda', 'negative'),
    ('Aí meu deus! Que sensação horrível', 'negative'),
    ('RT @brubismallet: Não da pra nem sai p rua, ta horrível', 'negative'),
    ('Vai pela sombra pq merda seca no sol.[7323]', 'negative'),
    ('merda hoje eu faria um ano de namoro', 'negative'),
    ('Horrível quando você quer ver sua sobrinha mas tá de castigo', 'negative'),
    ('2015 foi um ano horrível', 'negative'),
    ('RT @loiradanielli: Homem que não sabe dar valor ao que tem, acaba sozinho, comendo piranha e fingindo que é feliz...', 'negative'),
    ('RT @jorginhoben10: eu nao acho ruim voce se gorda mas voce ocupa o luga de tres pessoa e sacanagem', 'negative'),
    ('É horrível se sentir sozinho, péssimo perceber que ninguém precisa de você...', 'negative'),
    ('Leo sem celular e horrível', 'negative'),
    ('Passei mal de madrugada, tive um sonho horrível', 'negative'),
    ('me acordar pra receber correspondência é muita sacanagem', 'negative'),
    ('Cara, 3x0 era um resultado injusto pra esse nosso primeiro tempo, time jogou fácil mas não mata o jogo, corremos riscos.', 'negative'), 
    ('Ficar sem sinal e sem internet é horrível ...', 'negative'),
    ('que dor de garganta horrível', 'negative'),
    ('RT @humdaora: "se ainda stalkeia é sinal que não superou" nada a ver, as vezes a gente stalkeia só p ver se a pessoa já ta tomando no cu, o…', 'negative'),
    ('Pleno sabado eu deveria estar transando e to aqui deitada no sofá esperando a morte vir me buscar', 'negative'),
    ('Amigo coxinha, #NãoParticipeDoGolpe pq qdo essa "modinha" acabar e vc perceber q ridículo foi, eu vou continuar rindo mt do mico q vc pagou.', 'negative'),
    ('@O_pereiratois Concordo! Acho ridículo essas atitudes, me faz pensar o quão mentiroso (a) uma pessoa pode ser ! Mas faz parte,"a fila anda"', 'negative'),
    ('A fulana chama chama a outra fulana de "piranha" queridaaaaa onde está o amor próprio?', 'negative'),
    ('2015 tem cada desenho novos ridículo da nem vontade de volta a ser criança', 'negative'),
    ('@elisa_sfr me desculpe me intrometer mas isso ta ridículo criticando o cara porque ele ta seguindo em frente e pior sao pessoas ja vividas', 'negative'),
    ('@Mellojapa_carol postou uma foto ridícula minha no tt', 'negative'),
    ('Garganta ruim..', 'negative'),
    ('Acordei com a garganta ruim, graças ao ar condicionado', 'negative'),
    ('RT @surtossurreais: Que morte horrível não conseguir dormir.', 'negative'),
    ('RT @FatosEx: vc tem cara de ser uma pessoa mt ruim fria e que vai acabar com minha vida ', 'negative'),
    ('RT @stwrtdalla: muito ruim quando vc ta de boa ai você pisca nao ta mais de boa ta ansiosa sua auto estima ta no chão e vc fica perdida sem…', 'negative'),
    ('A morte e a morte de Marília Pêra https://t.co/I49IieDwwn', 'negative'),
    ('Entrar no tt e levar porrada de spoiler de TO. Que morte horrível!', 'negative'),
    ('É a morte esse vestibular da uepg amanhã e segunda. ', 'negative'),
    ('Me enfio em cada fria que só por deus mesmo.', 'negative'),
    ('Fui cortar o cabelo e to ridícula', 'negative'),
    ('To bom não, aquela parada de ir no role e misturar cerveja da ruim!', 'negative'),
    ('Odeio awkward moments, é tão péssimo', 'negative'),
    ('Te perder de vista assim, é ruim demais', 'negative'),
    ('RT @stwrtdalla: muito ruim quando vc ta de boa ai você pisca nao ta mais de boa ta ansiosa sua auto estima ta no chão e vc fica perdida sem…', 'negative'),
    ('Como se fizesse diferença o que você acha ruim, como se eu tivesse prometido alguma coisa pra você.', 'negative'),
    ('Sou tão ruim com a Nicole que eu fico até com dó', 'negative'),
    ('RT @luancosta17: Tem que gente é tão ruim que mesmo tendo 2 caras, nenhuma presta.', 'negative'),
    ('Muito ruim pegar nojo de pessoas que você considerava', 'negative'),
    ('RT @vishdoidao: Você atingiu 100% do seu pacote de ridícula pfvr agora de um tempo', 'negative'),
    ('ruim dms atribuir uma música a uma pessoa', 'negative'),
    ('muito ruim isso de ter que pagar contas quem inventou essa besteira', 'negative'),
    ('RT @victoriaborri: vc dizia q eu era ruim e arranjou outro pior do q eu', 'negative'),
    ('Que clima ruim, pqp', 'negative'),
    ('Mais uma morte pós festa na USP! Até quando ? Antro...', 'negative'),
    ('Não sei porque diabos a letra do meu coisa tá ruim', 'negative'),
    ('@laraccsl caraca piranha falei que era pra estudar mais', 'negative'),
    ('Ai se sou eu, eu sou ruim!', 'negative'),
    ('Mor ruim esse travesseiro da nasa aqui mano', 'negative'),
    ('Meu twitter cismou de dar ruim logo hj', 'negative'),
    ('Pedi um drink muito ruim pqp', 'negative'),
    ('Lado ruim de usar óculos novo: antes eu não via as sujeirinhas no chão, agora eu vejo esse piso cheio de cabelos e pelo de gato...', 'negative'),
    ('RT @perpich157: Estou tão cansada, hoje eu vou sofrer viado...muita coisa pra resolver...E fazer, e mais os eventos da noite, cansativo...m…', 'negative'),
    ('RT @femininjask: TUDO ISSO é você exigir da pessoa uma atenção irrestrita pra que ela não seja culpada de "te fazer de trouxa"', 'negative'),
    ('So acho que sexta vou trabalhar muito cansado', 'negative'),
    ('Cara ficou MT feia a minha boca!! E ta doendo demais', 'negative'),
    ('RT @noss4gi: Não tem morte pior do que tirar 18388292 fotos e sair bem naquela em que não da pra ver seu rosto', 'negative'),
    ('muito ruim ler algumas coisas', 'negative'),
    ('RT @romanticotche: Quando eu pego o celular e não tem nenhuma mensagem me sinto abandonado numa ilha deserta sozinho DEIXADO A MORTE', 'negative'),
    ('Eu lembro até hoje de quem me deu parabéns e quem não me deu. Eu sou ruim, não dou parabéns p uma pessoa q não deu no meu', 'negative'),
    ('Por favor, evitem trocadilhos com meu sobrenome, tipo, você me Mattos de tesão. Sério. É muito ruim.', 'negative'),
    ('RT @inescarvalho55: É péssimo qnd n tens assunto c a pessoa q qrs falar', 'negative'),
    ('a única coisa ruim que aconteceu ontem foi que machuquei meu pé feio', 'negative'),
    ('O dia tá péssimo', 'negative'),
    ('Já acordo com noticia ruim tmnc td final de ano acontece alguma coisa...', 'negative'),
    ('Minha irmã tá vendo MTV e eu me pergunto como esse canal ficou tão ridículo de uns 10 anos pra cá', 'negative'),
    ('quem a vaness pensa que é pra alem de escutar musica do nbhd QUE ELA CHAMAVA DE RUIM e ainda colocar icon do canto', 'negative'),
    ('@cassiamenezz_ q feia essa xenofobia, vou te jogar nos grupos pra vc ser denunciada até perder o perfil', 'negative'),
    ('RT @bipolauren: O quão ridículo são aqueles caras que acreditam que o pinto deles é a divindade que desceu do céu e ficam ostentando o próp…', 'negative'),
    ('que porra hoje vai ter show do R5 e eu como sempre nao vou a vida e bastante desprazerosa muito ruim viver assim', 'negative'),
    ('Que dia horrível... Minha cunhada morreu na minha casa....', 'negative'),
    ('Minha irmã acaba com sua auto estima em uma frase e ela ta "só te ajudando" mas você fala uma palavra pra ela e você é a grossa, a ridícula', 'negative'),
    ('RT @ficantefalando: Tô cansado de vc me tratar assim', 'negative'),
    ('Não sei qual a doença de postar tudo no face, gente para que ta feio.', 'negative'),
    ('Dor nas costas ruim do crl', 'negative'),
    ('fala mal do meu aparelho como se fosse uma coisa ruim, pelo menos não esses dentes separados e escrotos', 'negative'),
    ('Péssimo atendimento no @applebees_poa. Ficamos 10 minutos sentados e nenhum garçom foi capaz de aparecer nem pra fazer o pedido de bebidas!', 'negative'),
    ('RT @aiaiai63: "puxa, tem uma notícia boa da gestão Haddad...vamo dá mas arruma um jeito de parecer ruim." https://t.co/CPUkp2ovdP', 'negative'),
    ('@felipeneto A mídia acabou com a Cultura. Agr nada relevante mais quem e Michel Teló comparado a Seu jorge. Pq Renato russo morreu cedo???', 'negative'),
    ('@MatheusMh11 Ele nem tem culpa do time jogar um futebol ridículo e ser eliminado na primeira fase da UCL não. Coisa da minha mente', 'negative'),
    ('RT @girlsimgs: amiga não é recalque de vc, é que realmente vc é ridícula desculpa a sinceridade', 'negative'),
    ('Lucas sempre com cara de cansado LucasLuccoNoCaldeirao', 'negative'),
    ('RT @neymarjr: Chateado, estou cansado de tudo !', 'negative'),
    ('Pelo menos o carinha q era otário se deu bem no final. Não posso dizer o mesmo da minha situação.', 'negative'),
    ('RT @lrvesgo: uai gente a pessoa pergunta se o fc ta bom e se falam que ta feio ela acha ruim, querida se n quer saber não pergunta', 'negative'),
    ('E essa gente forçando algo que não é, não existe algo mais ridículo do que isso', 'negative'),
    ('para q ta feio gabriela', 'negative'),
    ('RT @flashetero: não sei como vocês consegue gostar de scream queens é muito ruim', 'negative'),
    ('@avrilskins o ruim é q povo de humanas tem aquilo de fumar e beber demais, maconha, cerveja, etc.. E tem aquilo de poliamor.. N gosto disso', 'negative'),
    ('alguem avisa o lucas pra tirar esse bigode feio', 'negative'),
    ('RT @girlaws: meu cu chora toda vez que vejo blusinha sem estampa de uma cor só de paninho ruim 39 reais', 'negative'),
    ('@5HFarofa quase ligo pra minha mãe chorando, EU SOU UMA PÉSSIMA DONA MEU DEUS', 'negative'),
    ('sei como é ruim tu chorando atoa, e aquela pessoa tá sorrindo numa boa...', 'negative'),
    ('Sério que calor ridículo é esse', 'negative'),
    ('Gengibre é tão ruim', 'negative'),
    ('É tão ruim não ter dinheiro. OH vida de cão', 'negative'),
    ('Fica falando cada coisa ridícula', 'negative'),
    ('depois de lasanha, panetone é a comida mais ruim que existe', 'negative'),
    ('Bateu uma parada ruim agora', 'negative'),
    ('fiquei puta e vim embora, sacanagem', 'negative'),
    ('RT @bpldadepre: Se tá ruim pra você, torcedor red devil, imagine para aqueles times ricos que estão brigando na parte de baixo da tabela...…', 'negative'),
    ('@folha que coisa feia Folha!', 'negative'),
    ('RT @Itspedrito: hoje eu to mais cansada que a soma de todos os tweets da Luciana Gimenez com a palavra "exausta"', 'negative'),
    ('Fiquei um pouco otário faz-pouco-caso de tanto levar tapa nos ultimos anos. Desculpa por isso.', 'negative'),
    ('@redrumgiu @GabAugusto é fácil se você faz isso desde pirralha mas eu sou ruim demais', 'negative'),
    ('Depois de uma noite tão boa como ontem, um dia destes de merda a seguir é péssimo', 'negative'),
    ('Pegar trânsito num sábado pra voltar pra casa é sacanagem', 'negative'),
    ('RT @QenheVC: O ruim de ser irônico com gente burra é que se a pessoa não entende quem fica parecendo burro é você', 'negative'),
    ('@blogdojotace dois meses depois lançaram os exemplares! Eu besta comprei um usado confiando na palavra da Panini.', 'negative'),
    ('eu tô tão cansada de mim, da rotina, de todos, da vida', 'negative'),
    ('RT @FrasesDeRenato: Aí do nada você se distanciou e eu fiquei aqui perdido...', 'negative'),
    ('Briguei bem feio com a minha mãe essa semana, mano não tinha necessidade ela falar aquilo pra mim', 'negative'),
    ('RT @dissefalsiane: odeio quando eu digo q to cansado e alguém diz "cansado de que?" AMG EU NAO PRECISO TER UM MOTIVO, EU TO CANSADO E PONTO', 'negative'),
    ('Sem contar que o atendimento desse hospital da unimed é péssimo', 'negative'),
    ('RT @ShaiBrito: Eu demoro pra enxergar o lado ruim das pessoas, mas depois que eu enxergo, elas podem chorar sangue que não me convencem mai…', 'negative'),
    ('Cansada dessa bad', 'negative'),
    ('@Alexfeernandees fiquei boladona. Já chegou me acordando e achando que estava certa.. muito ruim esse negocio de irmã mais velha.', 'negative'),
    ('Acho q briguei com meu pai em um péssimo dia, q merdaaa', 'negative'),
    ('RT @BerthDurango: Quando vc passar na rua e ficarem te olhando.. .Nao se sinta o maximo..  Pois o feio e o ridiculo tbm chamam a atenção .', 'negative'),
    ('mt ruim ficar pensando em uma coisa q nem aconteceu mas q só de pensar já te deixa mal pra caralho', 'negative'),
    ('Pior coisa do ano foi ter perdido meu riocard PQP', 'negative'),
    ('RT @FTCuriosos: TODOS os alunos de uma escola no Texas se juntaram para consolar um colega, depois que a mãe dele morreu de Câncer. https:/…', 'negative'),
    ('esses artigos "não namore uma garota/um garoto que..." ou "namore uma garota/um garoto que..." gente, para que tá feio isso!', 'negative'),
    ('RT @twittandopravc_: Caráter feio estraga rostinho bonito, se liga.', 'negative'),
    ('RT @CHB_WestRap: Pq todo sábado é ruim?', 'negative'),
    ('irmao, pior de tudo eh eu querer usar o wpp e só poder usar ele no computador... e o notbook estar estragado!!! ta certim', 'negative'),
    ('Acabei de jogar a pior partida da minha vida no @Battlefield', 'negative'),
    ('RT @IsadoraLunar: O @twitter no Windows Phone é a pior coisa que existe, e eu que uso o Twitter praticamente o dia inteiro acabo me ferrand…', 'negative'),
    ('RT @Cruzoeiro: Na boa, é sério isso aqui? Atleticano tem uma doença pior que câncer na boa. https://t.co/kzjUv9udFW', 'negative'),
    ('lembrei que eu dei uma volta nos amigos do x tudo del márcio ontém e tô péssima viu', 'negative'),
    ('pedi um coque like vitoria does mas ela disse q ia ficar feio e prendeu o meu cabelo todo p um lado so??? tipo AF', 'negative'),
    ('Ela assim, "outros"  pessoas, eu aqui... Noite ruim.', 'negative'),
    ('RT @LennonBossa_: NÃO TEM COISA PIOR DO QUE FICAR LONGE DE QUEM A GENTE AMA', 'negative'),
    ('odeio quando minha mãe sai e n atende o telefone, fico perdida em casa sozinha', 'negative'),
    ('RT @_mareanas: FAST AÇAÍ É MUITO RUIM', 'negative'),
    ('A cada dia é um dia pior aqui em casa.', 'negative'),
    ('RT @thamitirando: é bem ruim quando vc tá confiante numa coisa e PLAU', 'negative'),
    ('RT @_eujohn7: pior sábado!!!', 'negative'),
    ('@taehospicio so musica ruim pqp', 'negative'),
    ('RT @PastorMalafaia: Vamos orar pelo Brasil , a coisa está feia, um desgoverno, uma incompetência total.Quem paga o pato é o povo.Fora Dilma…', 'negative'),
    ('@arrobadebo miga seu crush raspou a cabeça tá mt feio', 'negative'),
    ('Lado ruim da cirurgia: passar mais de 2 meses sem tocar violão :(', 'negative'),
    ('RT @OpsGrazi_: Timidez e a pior merda pra vc pode ter', 'negative'),
    ('@pxcifyhim Se você for comprar aqureles cliker cuidado pra não comprar pequeno igual a anta aqui mt ruim doe pfa crl', 'negative'),
    ('Acordei agr, e vi que ta chovendo, esse tempo ta de sacanagem', 'negative'),
    ('Tem muita coisa ruim sendo compartilhada.', 'negative'),
    ('RT @amandamoura78: Deus que me perdoe, mas sinto muita raiva dessas paradas..o pior e ver essas garotas rindo', 'negative'),
    ('Otro fin de semana perdido.', 'negative'),
    ('Deus me dê muita força. Cheguei no meu limite mesmo. Se acontecer algo mais de ruim, sinceramente, não irei suportar.', 'negative'),
    ('Mas você é besta mesmo neh', 'negative'),
    ('Se você quer, chega junto, não fica em cima do muro com orgulho besta, p merda', 'negative'),
    ('Rolando karaokê especial Reginaldo Rossi no salão do meu prédio, mas parece q tão cantando dentro da minha casa ou pior no meu quarto.', 'negative'),
    ('RT @Larissa23256014: Só falta acabar a energia pra ficar pior.', 'negative'),
    ('Mt ruim sair de casa sozinha, medo da porra de pegar trem essa hora e descer naquela estação horrivel do meier', 'negative'),
    ('teve um show de fogos aqui agora que minha cachorra só quase morreu', 'negative'),
    ('essa fanfic além de ser ruim ainda tem parte 2 COMO PODE', 'negative'),
    ('Minha tosse tá pior que a minha vó fumante, meu peito dói, minha cabeça dói e tô com febre pra piorar tudo .-.', 'negative')
]
