positive_tweets = \
[
    ('Mais se hoje tudo der certo, vai dar amor!!', 'positive'),
    ('RT @frasesdebebada: tomara que a luz no fim do túnel seja uma geladeira de cerveja aberta', 'positive'),
    ('RT @mulequidoidu: Meu amor, eu juro Ser teu e de mais ninguém https://t.co/01wifAmCBq', 'positive'),
    ('É hoje', 'positive'),
    ('10 maneiras de curtir ao máximo a festa da firma  https://t.co/ZTHg2Zpu61 via @CatracaLivre', 'positive'),
    ('Quem procura um espumante pra sua festa de casamento procura qualidade, preco e uma garrafa… https://t.co/1g1U2QGHgU', 'positive'),
    ('@versosaoluan obrigada amor ! maravilhosa né', 'positive'),
    ('RT @Kefera: Amor de fã é foda!', 'positive'),
    ('RT @relatojovens: Olhe para o Céu o Amor vem de lá', 'positive'),
    ('eu fui pedir desculpas pra mina sobre ter mandado uma mensagem trovando ela bebada depois da festa e agr ela quer ficar comigo kkkkk', 'positive'),
    ('ai ai amor, me leva contigo que vou', 'positive'),
    ('RT @relatojovens: Amor não é só beijos e amassos, Amor é cuidado, amor é carinho, Amor também é amizade.', 'positive'),
    ('E ainda to descobrindo aos poucos como foi a festa ontem', 'positive'),
    ('RT @Euu_Emily: De sábado!', 'positive'),
    ('Maninha virá ao RJ ano que vem, AMC,  felicidade', 'positive'),
    ('RT @9090rap: Desejo a todos paz, amor e muita sacanagem.', 'positive'),
    ('@Putanetels Seguindo amor, segue de volta? #5AnosLSAoVivoNoRio', 'positive'),
    ('Um Amor correspondido é a melhor coisa ..', 'positive'),
    ('Sexta feira e dia de amor vim pra minha casa', 'positive'),
    ('Monica pelo amor de deus não dança veio venha pra minha cama #VideoShowAoVivo', 'positive'),
    ('RT @aniruffles: VEEEEM BEIJOS, VEM PEGAÇÃO, VEM SUCESSO, VEM TTCAM, VEM ENTREVISTAS, VEM IMAS, VEMMMM LOGO 2016 PAREJA TEKILA IS BACK', 'positive'),
    ('FESTA DA PADROEIRA SANTA LUZIA - 10 A 13 DE DEZEMBRO https://t.co/aHgWmHDvN3', 'positive'),
    ('@lanadelkatyy klsçks legal amor, podia chegar logo ne', 'positive'),
    ('RT @falsianecobra: Ai você vai no banheiro de uma festa. Sai de lá rindo, com 12 novas amigas, telefones trocados, e uma viagem marcada', 'positive'),
    ('"E quando o mundo for guerra, serei sua paz"', 'positive'),
    ('RT @UmVingador: se o amor bateu na nossa porta, que sorte a nossa', 'positive'),
    ('RT @BonnieDiva: @FalaHoldz te amo amor', 'positive'),
    ('RT @ttwitandu: dezembro é o melhor mês do ano por 4 motivos: 1- férias 2-natal 3-festa 4-comida', 'positive'),
    ('A felicidade é tanta que nem cabe no peito. @victoriaruffo31 #CésarEvora AMO VOCÊS!', 'positive'),
    ('RT @pqmillen: É tanto campeão mundial que até o Rogério cumprimentar todo mundo acabou a festa', 'positive'),
    ('meu cabelo tá tão amor', 'positive'),
    ('Ta muito bom pra ser verdade a casa sem meus pais, sem meus sobrinhos, ohhh paz', 'positive'),
    ('RT @RimouCacife: Eu só quero paz, um amor e uns amigos leais.', 'positive'),
    ('RT @SouNamaste: E o teu sorriso, é o meu ponto de paz.', 'positive'),
    ('RT @secretsiozzi: Minha mãe disse que a @Srta_Iozzi não sabe disfarçar o amor que ela tem pelo @otacosta hahahahahahaha #VideoShowAoVivo', 'positive'),
    ('RT @pipaa___: és o amor da minha vida.... nutella', 'positive'),
    ('RT @RelateiRap: É sexta-feira irmão. Relaxa e fica suave, hoje vai ser só felicidade.', 'positive'),
    ('RT @outonismo: Consideramos justa toda forma de amor', 'positive'),
    ('vou fazer coisa no cabelo pra ir pra festa hoje abalando', 'positive'),
    ('@WesleySafadao MEU AMOR TE AMO VOCE EH MEU ORGULHO', 'positive'),
    ('Isso é amor ta rolando amor....', 'positive'),
    ('RT @vitti_joao: @vittipeace , vem sentir o calor e a amizade dos Raios Solares! Seja bem vinda!', 'positive'),
    ('RT @Apaixon4do: Quando o amor é forte, nem toda inveja do mundo é capaz de destruir.', 'positive'),
    ('Transbordando felicidade. Esses são alguns dos alunos do Projeto de Ginástica Aquarela para a terceira idade, que... https://t.co/SLX4l63Hs7', 'positive'),
    ('Omg a cara dele de felicidade eu n aguento!!!!!!!!!!!!!!! https://t.co/7pMsyY6Uxh', 'positive'),
    ('RT @carolarantesd: Amor tem que ser overdose', 'positive'),
    ('RT @surtossurreais: Felicidade é aquilo quando estamos dormindo.', 'positive'),
    ('RT @honeypict: Amor (aquário): Hoje estará apto para novas ideias. O carinho e a atenção reinarão na sua relação afetiva. https://t.co/kLlI…', 'positive'),
    ('RT @Leia_a_Biblia: (Salmos 91:11) - Porque aos seus anjos dará ordem a teu respeito, para te guardarem em todos os teus caminhos.', 'positive'),
    ('@nanaribsil @paulo_gobbi @Marisb_4 festa da meeeeel e da Alice', 'positive'),
    ('Queria uma cerveja, super gelada.', 'positive'),
    ('RT @kah_gusmao: Uma das boas notícias você já recebeu , só falta mais uma meu amor , e logo lá vem @kilmes_', 'positive'),
    ('RT @ArelyTellez: Me encanta https://t.co/W6xzRzM4Zw', 'positive'),
    ('RT @dontsstop_: "deixa eu te elogiar sem ser elogiada" lari é amor', 'positive'),
    ('RT @divregente: wesley safadão um amor de pessoa respondendo os fãs https://t.co/g1fWtEWSie', 'positive'),
    ('Parabéns Evandro de Azevedo muito sucesso em sua profissão! https://t.co/fQsxuxBw30', 'positive'),
    ('Ultimamente eu só tenho a agradecer a Deus por tudo. Por cada coisa que ele tem me feito passar, seja boa ou ruim, tudo tem um aprendizado.', 'positive'),
    ('Nunca se esqueça nem um segundo Que eu tenho o amor maior do mundo', 'positive'),
    ('RT @BialCitou: As coisas vão dar certo. Vai ter amor, vai ter fé, vai ter paz!', 'positive'),
    ('RT @ConexaoCristao: Foi o Teu amor, o Teu amor, incondicional, foi o Teu amor, o Teu amor, faz tudo novo, quebranta o meu coração', 'positive'),
    ('Q AMOR, Q LINDO.. EU QUERO https://t.co/DjsUNN0OCC', 'positive'),
    ('RT @Bebadosfalando: QUERO UMA FESTA QUE DURE 3 DIAS', 'positive'),
    ('A felicidade só é real quando compartilhada... #Supertramp', 'positive'),
    ('RT @VITORIA13SWIFT: #1989TourBrazil A esperança é a ultima que morre !!! Taylor vem logooo nunca te pedi nada', 'positive'),
    ('RT @selenagomezbr: “Eu amo a Lady Gaga! Ela sempre é um amor comigo e eu quero que ela faça um grande discurso porque ela é ótima para as m…', 'positive'),
    ('#RickCampeão  parabéns pelo seu trabalho e esforço vc merece', 'positive'),
    ('RT @michele230799: Quero logo a festa da maria', 'positive'),
    ('E amor depois vc não quer que eu engorde né kkk brincadeira o bombons estavam ótimos.. https://t.co/PeVslfhDww', 'positive'),
    ('Hoje mais alem tem festa.', 'positive'),
    ('RT @shesconfidewt: Eu amo o Gabriel mais que td sério,é um amor que nem cabe dentro de mim', 'positive'),
    ('@horanpelada meu amor muito obrigada', 'positive'),
    ('@Rayypereira1 Baixa Alvin e os esquilos meu amor, hsuahsuhaushuah', 'positive'),
    ('A minha mãe oferecerme o bilhete para o concerto do justin omd. Sentem a minha felicidade?', 'positive'),
    ('RT @Dig_tyf: Mas quando a gente se encontra, o amor sempre apronta. O que posso fazer?', 'positive'),
    ('RT @ruffosmile: A felicidade é tanta que nem cabe no peito. @victoriaruffo31 #CésarEvora AMO VOCÊS!', 'positive'),
    ('O verdadeiro amor, nasce em tempos difíceis ..', 'positive'),
    ('RT @nayroddrigues: Quero logo ver meu amor, anem gente', 'positive'),
    ('Microsoft ganha desafio de tecnologia de reconhecimento de imagem: https://t.co/1sgyAkuJne https://t.co/6apyjFnEmr', 'positive'),
    ('aprendi a tocar black dog do led zeppelin, que felicidade', 'positive'),
    ('RT @ticoelias1: #HexaNaFavela foi um sonho realizado. Agora é preciso descansar para dobrar o sucesso passado! #ObrigadoDeus #ObrigadoFiel', 'positive'),
    ('Nada pode impedir sua grandeza ao acreditar em si mesmo como modelador de sucesso e propulsor da própria felicidade.', 'positive'),
    ('RT @CNDLA5H: NÃO HÁ PALAVRAS NO MUNDO CAPAZ DE EXPRESSAR TANTO AMOR!! @FifthHarmony  #WomenInMusic #5HGroupoftheYear! https://t.co/VI…', 'positive'),
    ('@larryshippou obrigada amor!', 'positive'),
    ('Aquela cerveja de leve com a família só pra começar a sexta feira', 'positive'),
    ('Anos se passam mas o meu amor pelo o Fresno não acaba só aumenta', 'positive'),
    ('RT @vem_sexo: Quando o amor te rejeita , a putaria te aceita', 'positive'),
    ('Sexta combina com cerveja e Usina! Então Bora porque hoje tem Diego Bartelli no comando, e… https://t.co/eqk2ebE7in https://t.co/JxnQO62b3J', 'positive'),
    ('RT @GustavoBessa4: Combinação perfeita é Sexo, Cerveja e Maconha', 'positive'),
    ('RT @jauregui9821: Coração tá disparado na expectativa da Lauren conhecer a Lana!!! Vai que é tua Lauren kkkkkkk Group of the Year #5HGroupO…', 'positive'),
    ('Sexta é dia de... #biritis! Clica aí e saiba mais sobre a cerveja do Mussum com os caras que… https://t.co/N27xFgNNGO', 'positive'),
    ('Gostei de um vídeo @YouTube de @wamorim_ https://t.co/TiDMEZ9XKL CLUBE DA LUTA #02 (FEAT. PERTURBANDO A PAZ)', 'positive'),
    ('Melhor fim de aulas era impossível, esperamos por ti!!', 'positive'),
    ('Isso é amizade de verdade. https://t.co/XHcdrRZFFL', 'positive'),
    ('Quando alguém fala: "Se vira, da seus pulo ai!" e você faz o desafio melhor que imaginava https://t.co/lEBmWmJEhS', 'positive'),
    ('RT @AngelicaMelo8: Foca na FELICIDADE dos donos da galáxia! https://t.co/RuLfyq3p08', 'positive'),
    ('RT @SintoniaVerso: Que os ventos soprem a favor da nossa felicidade', 'positive'),
    ('RT @17h25: Eu ainda to na esperança de alguém entrar na minha vida e salvar 2015', 'positive'),
    ('Linda essa atitude dele, um dos poucos que merece o verdadeiro respeito desse meio, esse cara é foda https://t.co/Y8LjpTXtd3', 'positive'),
    ('RT @truebaek: O JONGIN DANÇANDO VCS ME DESCULPA MAS NO KPOP N EXISTE UMA ALMA QUE DANCE COM MAIS PAIXÃO QUE ESSE HOMEM NÃO #SingForYou', 'positive'),
    ('Gostei de um vídeo @YouTube de @eversonzoio https://t.co/5Bq1PDBKUO ENTRANDO NO ÔNIBUS DE BICICLETA DESAFIO #32', 'positive'),
    ('RT @FutNaRedonda: Quando o amigo chega falando que a cerveja tá na promoção: https://t.co/FlqNibTjAP', 'positive'),
    ('RT @VSertanejo: Recaí quando te vi a paixão veio à tona', 'positive'),
    ('Eu só me rio com eles, são os melhores!!  https://t.co/qjVJSNvePG', 'positive'),
    ('melhor coisa é quando tu desconfia da sexualidade da pessoa e ai tu vai numa festa com ela e tem certeza q ela é gay/bi', 'positive'),
    ('RT @diadiamengao: @CacaucottaLuis @TozzaFla @bruno_leivas @Renhato79 Falando em respeito com a instituição, o Cacau deu show nesse quesito.…', 'positive'),
    ('RT @ELacosdefita: Felicidade é poder ler livros assim tão lindos. #maisDoQueApaixonada #AmamosSRWilliamGabriel https://t.co/0vuzk0ufQx', 'positive'),
    ('O bom da minha amizade com a Jheni é que eu posso ser carinhosa 25 horas por dia que ela não enjoa, posso falar q amo ela td hora, e é p smp', 'positive'),
    ('Partiu morumbi #MariaMole #Cerveja #mito #alcoolatra #pinga #sovoltoamanha #vaicaraiw', 'positive'),
    ('RT @OBubaBalde: #TurmaQueETurma tem sempre aquela pessoa que diz " que silêncio " quando a turma toda está calada.', 'positive'),
    ('to comeno pao doce com coca primera felicidade do dia', 'positive'),
    ('a festa ta boa com 18 DLCs no shadows of mordor! https://t.co/GWbllKJypm', 'positive'),
    ('RT @AsVodkas: as amizades feitas no banheiro da festa não tem preço!', 'positive'),
    ('RT @_mmfh_: Vou falar que é amor, vou jurar que é paixão', 'positive'),
    ('Como se tudo fosse felicidade, eu seria um belo sorriso![9562]', 'positive'),
    ('Gatinho invade foto de família e bomba na web: Apesar do sucesso, a identidade do gato ainda é desconhecida, a... https://t.co/9sKxyKQy4O', 'positive'),
    ('@ItagibaFrancez Sensacionais essas imagens! Me faz lembrar a festa nos estádios no início do anos 90.', 'positive'),
    ('RT @EscolhiEsperar: Ser fiel não é uma questão de escolha, e sim de caráter.', 'positive'),
    ('@Sen_Cristovam Sempre tivemos esperança e orgulho de suas posturas na vida publica senador, não nos tire isso. Acreditamos no senhor.', 'positive'),
    ('RT @FicaDoMeuLado: Era pra ser só amizade, mais aí eu me apaixonei.', 'positive'),
    ('RT @_gabsmorelli: melhor festa surpresa do mundo, amo todos que vieram e os que não puderam vir', 'positive'),
    ('RT @RecitoBobMarIey: Apaixone-se por alguém que, mesmo com milhões de motivos pra ir, escolha ficar.', 'positive'),
    ('Cara, a festa do CTC ta a cada ano melhor', 'positive'),
    ('@marciofreudenbo @wesleyfsouza @Miranda50sonia @SakaSakamori @ElizaH0ffmann @Marlialvesf Bom dia amigos com paz e amor, abraços!', 'positive'),
    ('RT @RecitoBobMarIey: Idade é um número. Maturidade é escolha.', 'positive'),
    ('é bom saber que ela continua a confiar em mim... ela sabe que gosto bastante dela e que nunca iria trair a nossa amizade &lt;3', 'positive'),
    ('Caralho que festa foi aquela', 'positive'),
    ('RT @CatarinaLiz: Roupa e eu, eu e roupa, é um paixão eterna', 'positive'),
    ('RT @LARI_LOPES013: Shawn e Camila É FOFO SIM, MAS CAMILA É DA LOLO KIRIDON, AMO A AMIZADE DELES MAS ACEITEM QUE É SÓ AMIZADE .', 'positive'),
    ('a cura pro meu tédio, a direção, ela é a paz pro oriente médio do meu coração... @carol_laving', 'positive'),
    ('Ainda bem que fui naquela festa ontem pq encontrei o amor da minha vida lá', 'positive'),
    ('"So vives uma vez. Deixa-te de merdas e vai atras da felicidade como se nao houvesse amanha"', 'positive'),
    ('Aquele amor que nos constrange, nos arrebata, que nos faz mergulhar numa imensidão de paz e misericórdia', 'positive'),
    ('RT @AdrianaArydes: #minisermao Quem tem o céu no coração transforma até as dores em canção e contagia com a esperança do amanhecer que virá…', 'positive'),
    ('Nossa oração contínua, deve ser a Deus, pedindo sempre sabedoria em tudo, todos os dias.... https://t.co/40WwCYKWvz', 'positive'),
    ('RT @stylescrushado: impossível esquecer a felicidade deles quando cantaram no control pela primeira vez https://t.co/AeIbhJdxxN', 'positive'),
    ('@isamaradd Dê Glória a Deus! E diga que o resultado do seu esforço é graças a Ele! Sem a presença do Senhor nada podemos fazer.', 'positive'),
    ('@dinhamoraes1 bom que 2 copinhos de cerveja agora reativa a onda de ontem! Kkkkk', 'positive'),
    ('O Ray me conhece a uma semana e parece que a nossa amizade é de anos.', 'positive'),
    ('RT @versosdampb: Dia de luz, festa do sol, um barquinho a deslizar, no macio azul do mar.', 'positive'),
    ('Que festa FODA. Set de 3 horas do #lowception fechando a noite das 5:30 as 8:30 da manha num lugar irado hahaha https://t.co/oUbt5zrh47', 'positive'),
    ('A humildade é a parte mais bela da sabedoria.', 'positive'),
    ('RT @FoxSports_br: Já já começa o segundo tempo do jogo de despedida de Rogério Ceni! A festa continua no Morumbi! #PraSempreM1TO https://t.…', 'positive'),
    ('RT @bibssouza: Fiz amizade c tanta gente legal', 'positive'),
    ('RT @RecitoBobMarIey: Consciência limpa é a melhor coisa. A paz de encostar a cabeça no travesseiro e ficar tranquilo com as próprias atitud…', 'positive'),
    ('Bom dia! Graça e paz seja contigo.', 'positive'),
    ('RT @projetoshadow: não importa a sua preferência, ambos os cast são ótimos e merecem o nosso carinho e respeito #1MonthToShadowhunters http…', 'positive'),
    ('RT @DREWITHITS: eu espero q ano q vem entre alguém bem foda das galaxia lá na escola pra nós fazer amizade #askbelieber"esperamos', 'positive'),
    ('RT @AsVodkas: Aponta pra festa open bar e rema.', 'positive'),
    ('O melhor de ir pra festa é ir pra incomodar', 'positive'),
    ('RT @ItagibaFrancez: Essa cena eu não via a 30 anos e ontem tive a felicidade de relembrar um pouco do passado !! Muito obrigado ! https://t…', 'positive'),
    ('RT @VladimirAlves: Dinheiro é bom, ajuda, faz rir? Claro! Mas ter amor e respeito pelo próximo e animais, te fazem uma milionária na vida r…', 'positive'),
    ('@ashpurpurina boa festa irmã! Tomara q aconteça uns bafão pra depois vc me contar', 'positive'),
    ('RT @mtnaikkk: "Na alegria e na tristeza é você e eu, na saúde ou na doença você e eu. Ah é só você e eu" Feliz dia 12 minha linda @eloaney', 'positive'),
    ('Parabéns Silvio Santos esse merece meu respeito... Desejo toda felicidade.', 'positive'),
    ('Publiquei 19 fotos no Facebook no álbum "FESTA DA TIA TAI- A GRANDE FAMÍLIA! AUHAUHAUAHUAHUAHUAHUA!" https://t.co/Z37fiZ8iHs', 'positive'),
    ('Uma coisa boa da crise: se bebe (cerveja) e se come (churrasco) menos. A saúde agradece.', 'positive'),
    ('RT @JOAQUINTDASILVA: APROVEITEM O FINAL DE SEMANA COM RESPONSABILIDADE: NÃO USEM DROGAS, E SE SAIREM COM PROSTITUTAS OU TRAVESTIS USEM PRES…', 'positive'),
    ('RT @admnews: 7 dicas para montar uma apresentação de sucesso em pouco tempo https://t.co/ba5TRvoRPh', 'positive'),
    ('RT @CrlAdrielle: Bud é melhor cerveja!!', 'positive'),
    ('Queria esboçar a felicidade q eu estou por ter acabado o curso', 'positive'),
    ('Eu sigo! já aguardando! essa marca vai bombar!!! https://t.co/un4vxLzshx', 'positive'),
    ('john mayer nao tem uma musica ruim mano', 'positive'),
    ('RT @selectionado: isso é lindo, feio é o preconceito https://t.co/wdKLRHZgTx', 'positive'),
    ('Eu achava meu pé feio, mais depois de olhar os pés desses gringos to feliz com o meu. Kkk', 'positive')
]
    
    
    
