positive_tweets = \
[
    ('Mais se hoje tudo der certo, vai dar amor!!', 'positive'),
    ('RT @frasesdebebada: tomara que a luz no fim do túnel seja uma geladeira de cerveja aberta', 'positive'),
    ('RT @mulequidoidu: Meu amor, eu juro Ser teu e de mais ninguém https://t.co/01wifAmCBq', 'positive'),
    ('É hoje', 'positive'),
    ('10 maneiras de curtir ao máximo a festa da firma  https://t.co/ZTHg2Zpu61 via @CatracaLivre', 'positive'),
    ('Quem procura um espumante pra sua festa de casamento procura qualidade, preco e uma garrafa… https://t.co/1g1U2QGHgU', 'positive'),
    ('@versosaoluan obrigada amor ! maravilhosa né', 'positive'),
    ('RT @Kefera: Amor de fã é foda!', 'positive'),
    ('RT @relatojovens: Olhe para o Céu o Amor vem de lá', 'positive'),
    ('eu fui pedir desculpas pra mina sobre ter mandado uma mensagem trovando ela bebada depois da festa e agr ela quer ficar comigo kkkkk', 'positive'),
    ('ai ai amor, me leva contigo que vou', 'positive'),
    ('RT @relatojovens: Amor não é só beijos e amassos, Amor é cuidado, amor é carinho, Amor também é amizade.', 'positive'),
    ('E ainda to descobrindo aos poucos como foi a festa ontem', 'positive'),
    ('RT @Euu_Emily: De sábado!', 'positive'),
    ('Maninha virá ao RJ ano que vem, AMC,  felicidade', 'positive'),
    ('RT @9090rap: Desejo a todos paz, amor e muita sacanagem.', 'positive'),
    ('@Putanetels Seguindo amor, segue de volta? #5AnosLSAoVivoNoRio', 'positive'),
    ('Um Amor correspondido é a melhor coisa ..', 'positive'),
    ('Sexta feira e dia de amor vim pra minha casa', 'positive'),
    ('Monica pelo amor de deus não dança veio venha pra minha cama #VideoShowAoVivo', 'positive'),
    ('RT @aniruffles: VEEEEM BEIJOS, VEM PEGAÇÃO, VEM SUCESSO, VEM TTCAM, VEM ENTREVISTAS, VEM IMAS, VEMMMM LOGO 2016 PAREJA TEKILA IS BACK', 'positive'),
    ('FESTA DA PADROEIRA SANTA LUZIA - 10 A 13 DE DEZEMBRO https://t.co/aHgWmHDvN3', 'positive'),
    ('@lanadelkatyy klsçks legal amor, podia chegar logo ne', 'positive'),
    ('RT @falsianecobra: Ai você vai no banheiro de uma festa. Sai de lá rindo, com 12 novas amigas, telefones trocados, e uma viagem marcada', 'positive'),
    ('"E quando o mundo for guerra, serei sua paz"', 'positive'),
    ('RT @UmVingador: se o amor bateu na nossa porta, que sorte a nossa', 'positive'),
    ('RT @BonnieDiva: @FalaHoldz te amo amor', 'positive'),
    ('RT @ttwitandu: dezembro é o melhor mês do ano por 4 motivos: 1- férias 2-natal 3-festa 4-comida', 'positive'),
    ('A felicidade é tanta que nem cabe no peito. @victoriaruffo31 #CésarEvora AMO VOCÊS!', 'positive'),
    ('RT @pqmillen: É tanto campeão mundial que até o Rogério cumprimentar todo mundo acabou a festa', 'positive'),
    ('meu cabelo tá tão amor', 'positive'),
    ('Ta muito bom pra ser verdade a casa sem meus pais, sem meus sobrinhos, ohhh paz', 'positive'),
    ('RT @RimouCacife: Eu só quero paz, um amor e uns amigos leais.', 'positive'),
    ('RT @SouNamaste: E o teu sorriso, é o meu ponto de paz.', 'positive'),
    ('RT @secretsiozzi: Minha mãe disse que a @Srta_Iozzi não sabe disfarçar o amor que ela tem pelo @otacosta hahahahahahaha #VideoShowAoVivo', 'positive'),
    ('RT @pipaa___: és o amor da minha vida.... nutella', 'positive'),
    ('RT @RelateiRap: É sexta-feira irmão. Relaxa e fica suave, hoje vai ser só felicidade.', 'positive'),
    ('RT @outonismo: Consideramos justa toda forma de amor', 'positive'),
    ('vou fazer coisa no cabelo pra ir pra festa hoje abalando', 'positive'),
    ('@WesleySafadao MEU AMOR TE AMO VOCE EH MEU ORGULHO', 'positive'),
    ('Isso é amor ta rolando amor....', 'positive'),
    ('RT @vitti_joao: @vittipeace , vem sentir o calor e a amizade dos Raios Solares! Seja bem vinda!', 'positive'),
    ('RT @Apaixon4do: Quando o amor é forte, nem toda inveja do mundo é capaz de destruir.', 'positive'),
    ('Transbordando felicidade. Esses são alguns dos alunos do Projeto de Ginástica Aquarela para a terceira idade, que... https://t.co/SLX4l63Hs7', 'positive'),
    ('Omg a cara dele de felicidade eu n aguento!!!!!!!!!!!!!!! https://t.co/7pMsyY6Uxh', 'positive'),
    ('RT @carolarantesd: Amor tem que ser overdose', 'positive'),
    ('RT @surtossurreais: Felicidade é aquilo quando estamos dormindo.', 'positive'),
    ('RT @honeypict: Amor (aquário): Hoje estará apto para novas ideias. O carinho e a atenção reinarão na sua relação afetiva. https://t.co/kLlI…', 'positive'),
    ('RT @Leia_a_Biblia: (Salmos 91:11) - Porque aos seus anjos dará ordem a teu respeito, para te guardarem em todos os teus caminhos.', 'positive'),
    ('@nanaribsil @paulo_gobbi @Marisb_4 festa da meeeeel e da Alice', 'positive'),
    ('Queria uma cerveja, super gelada.', 'positive'),
    ('RT @kah_gusmao: Uma das boas notícias você já recebeu , só falta mais uma meu amor , e logo lá vem @kilmes_', 'positive'),
    ('RT @ArelyTellez: Me encanta https://t.co/W6xzRzM4Zw', 'positive'),
    ('RT @dontsstop_: "deixa eu te elogiar sem ser elogiada" lari é amor', 'positive'),
    ('RT @divregente: wesley safadão um amor de pessoa respondendo os fãs https://t.co/g1fWtEWSie', 'positive'),
    ('Parabéns Evandro de Azevedo muito sucesso em sua profissão! https://t.co/fQsxuxBw30', 'positive'),
    ('Ultimamente eu só tenho a agradecer a Deus por tudo. Por cada coisa que ele tem me feito passar, seja boa ou ruim, tudo tem um aprendizado.', 'positive'),
    ('Nunca se esqueça nem um segundo Que eu tenho o amor maior do mundo', 'positive'),
    ('RT @BialCitou: As coisas vão dar certo. Vai ter amor, vai ter fé, vai ter paz!', 'positive'),
    ('RT @ConexaoCristao: Foi o Teu amor, o Teu amor, incondicional, foi o Teu amor, o Teu amor, faz tudo novo, quebranta o meu coração', 'positive'),
    ('Q AMOR, Q LINDO.. EU QUERO https://t.co/DjsUNN0OCC', 'positive'),
    ('RT @Bebadosfalando: QUERO UMA FESTA QUE DURE 3 DIAS', 'positive'),
    ('A felicidade só é real quando compartilhada... #Supertramp', 'positive'),
    ('RT @VITORIA13SWIFT: #1989TourBrazil A esperança é a ultima que morre !!! Taylor vem logooo nunca te pedi nada', 'positive'),
    ('RT @selenagomezbr: “Eu amo a Lady Gaga! Ela sempre é um amor comigo e eu quero que ela faça um grande discurso porque ela é ótima para as m…', 'positive'),
    ('#RickCampeão  parabéns pelo seu trabalho e esforço vc merece', 'positive'),
    ('RT @michele230799: Quero logo a festa da maria', 'positive'),
    ('E amor depois vc não quer que eu engorde né kkk brincadeira o bombons estavam ótimos.. https://t.co/PeVslfhDww', 'positive'),
    ('Hoje mais alem tem festa.', 'positive'),
    ('RT @shesconfidewt: Eu amo o Gabriel mais que td sério,é um amor que nem cabe dentro de mim', 'positive'),
    ('@horanpelada meu amor muito obrigada', 'positive'),
    ('@Rayypereira1 Baixa Alvin e os esquilos meu amor, hsuahsuhaushuah', 'positive'),
    ('A minha mãe oferecerme o bilhete para o concerto do justin omd. Sentem a minha felicidade?', 'positive'),
    ('RT @Dig_tyf: Mas quando a gente se encontra, o amor sempre apronta. O que posso fazer?', 'positive'),
    ('RT @ruffosmile: A felicidade é tanta que nem cabe no peito. @victoriaruffo31 #CésarEvora AMO VOCÊS!', 'positive'),
    ('O verdadeiro amor, nasce em tempos difíceis ..', 'positive'),
    ('RT @nayroddrigues: Quero logo ver meu amor, anem gente', 'positive'),
    ('Microsoft ganha desafio de tecnologia de reconhecimento de imagem: https://t.co/1sgyAkuJne https://t.co/6apyjFnEmr', 'positive'),
    ('aprendi a tocar black dog do led zeppelin, que felicidade', 'positive'),
    ('RT @ticoelias1: #HexaNaFavela foi um sonho realizado. Agora é preciso descansar para dobrar o sucesso passado! #ObrigadoDeus #ObrigadoFiel', 'positive'),
    ('Nada pode impedir sua grandeza ao acreditar em si mesmo como modelador de sucesso e propulsor da própria felicidade.', 'positive'),
    ('RT @CNDLA5H: NÃO HÁ PALAVRAS NO MUNDO CAPAZ DE EXPRESSAR TANTO AMOR!! @FifthHarmony  #WomenInMusic #5HGroupoftheYear! https://t.co/VI…', 'positive'),
    ('@larryshippou obrigada amor!', 'positive'),
    ('Aquela cerveja de leve com a família só pra começar a sexta feira', 'positive'),
    ('Anos se passam mas o meu amor pelo o Fresno não acaba só aumenta', 'positive'),
    ('RT @vem_sexo: Quando o amor te rejeita , a putaria te aceita', 'positive'),
    ('Sexta combina com cerveja e Usina! Então Bora porque hoje tem Diego Bartelli no comando, e… https://t.co/eqk2ebE7in https://t.co/JxnQO62b3J', 'positive'),
    ('RT @GustavoBessa4: Combinação perfeita é Sexo, Cerveja e Maconha', 'positive'),
    ('RT @jauregui9821: Coração tá disparado na expectativa da Lauren conhecer a Lana!!! Vai que é tua Lauren kkkkkkk Group of the Year #5HGroupO…', 'positive'),
    ('Sexta é dia de... #biritis! Clica aí e saiba mais sobre a cerveja do Mussum com os caras que… https://t.co/N27xFgNNGO', 'positive'),
    ('Gostei de um vídeo @YouTube de @wamorim_ https://t.co/TiDMEZ9XKL CLUBE DA LUTA #02 (FEAT. PERTURBANDO A PAZ)', 'positive'),
    ('Melhor fim de aulas era impossível, esperamos por ti!!', 'positive'),
    ('Isso é amizade de verdade. https://t.co/XHcdrRZFFL', 'positive'),
    ('Quando alguém fala: "Se vira, da seus pulo ai!" e você faz o desafio melhor que imaginava https://t.co/lEBmWmJEhS', 'positive'),
    ('RT @AngelicaMelo8: Foca na FELICIDADE dos donos da galáxia! https://t.co/RuLfyq3p08', 'positive'),
    ('RT @SintoniaVerso: Que os ventos soprem a favor da nossa felicidade', 'positive'),
    ('RT @17h25: Eu ainda to na esperança de alguém entrar na minha vida e salvar 2015', 'positive'),
    ('Linda essa atitude dele, um dos poucos que merece o verdadeiro respeito desse meio, esse cara é foda https://t.co/Y8LjpTXtd3', 'positive'),
    ('RT @truebaek: O JONGIN DANÇANDO VCS ME DESCULPA MAS NO KPOP N EXISTE UMA ALMA QUE DANCE COM MAIS PAIXÃO QUE ESSE HOMEM NÃO #SingForYou', 'positive'),
    ('Gostei de um vídeo @YouTube de @eversonzoio https://t.co/5Bq1PDBKUO ENTRANDO NO ÔNIBUS DE BICICLETA DESAFIO #32', 'positive'),
    ('RT @FutNaRedonda: Quando o amigo chega falando que a cerveja tá na promoção: https://t.co/FlqNibTjAP', 'positive'),
    ('RT @VSertanejo: Recaí quando te vi a paixão veio à tona', 'positive'),
    ('Eu só me rio com eles, são os melhores!!  https://t.co/qjVJSNvePG', 'positive'),
    ('melhor coisa é quando tu desconfia da sexualidade da pessoa e ai tu vai numa festa com ela e tem certeza q ela é gay/bi', 'positive'),
    ('RT @diadiamengao: @CacaucottaLuis @TozzaFla @bruno_leivas @Renhato79 Falando em respeito com a instituição, o Cacau deu show nesse quesito.…', 'positive'),
    ('RT @ELacosdefita: Felicidade é poder ler livros assim tão lindos. #maisDoQueApaixonada #AmamosSRWilliamGabriel https://t.co/0vuzk0ufQx', 'positive'),
    ('O bom da minha amizade com a Jheni é que eu posso ser carinhosa 25 horas por dia que ela não enjoa, posso falar q amo ela td hora, e é p smp', 'positive'),
    ('Partiu morumbi #MariaMole #Cerveja #mito #alcoolatra #pinga #sovoltoamanha #vaicaraiw', 'positive'),
    ('RT @OBubaBalde: #TurmaQueETurma tem sempre aquela pessoa que diz " que silêncio " quando a turma toda está calada.', 'positive'),
    ('to comeno pao doce com coca primera felicidade do dia', 'positive'),
    ('a festa ta boa com 18 DLCs no shadows of mordor! https://t.co/GWbllKJypm', 'positive'),
    ('RT @AsVodkas: as amizades feitas no banheiro da festa não tem preço!', 'positive'),
    ('RT @_mmfh_: Vou falar que é amor, vou jurar que é paixão', 'positive'),
    ('Como se tudo fosse felicidade, eu seria um belo sorriso![9562]', 'positive'),
    ('Gatinho invade foto de família e bomba na web: Apesar do sucesso, a identidade do gato ainda é desconhecida, a... https://t.co/9sKxyKQy4O', 'positive'),
    ('@ItagibaFrancez Sensacionais essas imagens! Me faz lembrar a festa nos estádios no início do anos 90.', 'positive'),
    ('RT @EscolhiEsperar: Ser fiel não é uma questão de escolha, e sim de caráter.', 'positive'),
    ('@Sen_Cristovam Sempre tivemos esperança e orgulho de suas posturas na vida publica senador, não nos tire isso. Acreditamos no senhor.', 'positive'),
    ('RT @FicaDoMeuLado: Era pra ser só amizade, mais aí eu me apaixonei.', 'positive'),
    ('RT @_gabsmorelli: melhor festa surpresa do mundo, amo todos que vieram e os que não puderam vir', 'positive'),
    ('RT @RecitoBobMarIey: Apaixone-se por alguém que, mesmo com milhões de motivos pra ir, escolha ficar.', 'positive'),
    ('Cara, a festa do CTC ta a cada ano melhor', 'positive'),
    ('@marciofreudenbo @wesleyfsouza @Miranda50sonia @SakaSakamori @ElizaH0ffmann @Marlialvesf Bom dia amigos com paz e amor, abraços!', 'positive'),
    ('RT @RecitoBobMarIey: Idade é um número. Maturidade é escolha.', 'positive'),
    ('é bom saber que ela continua a confiar em mim... ela sabe que gosto bastante dela e que nunca iria trair a nossa amizade &lt;3', 'positive'),
    ('Caralho que festa foi aquela', 'positive'),
    ('RT @CatarinaLiz: Roupa e eu, eu e roupa, é um paixão eterna', 'positive'),
    ('RT @LARI_LOPES013: Shawn e Camila É FOFO SIM, MAS CAMILA É DA LOLO KIRIDON, AMO A AMIZADE DELES MAS ACEITEM QUE É SÓ AMIZADE .', 'positive'),
    ('a cura pro meu tédio, a direção, ela é a paz pro oriente médio do meu coração... @carol_laving', 'positive'),
    ('Ainda bem que fui naquela festa ontem pq encontrei o amor da minha vida lá', 'positive'),
    ('"So vives uma vez. Deixa-te de merdas e vai atras da felicidade como se nao houvesse amanha"', 'positive'),
    ('Aquele amor que nos constrange, nos arrebata, que nos faz mergulhar numa imensidão de paz e misericórdia', 'positive'),
    ('RT @AdrianaArydes: #minisermao Quem tem o céu no coração transforma até as dores em canção e contagia com a esperança do amanhecer que virá…', 'positive'),
    ('Nossa oração contínua, deve ser a Deus, pedindo sempre sabedoria em tudo, todos os dias.... https://t.co/40WwCYKWvz', 'positive'),
    ('RT @stylescrushado: impossível esquecer a felicidade deles quando cantaram no control pela primeira vez https://t.co/AeIbhJdxxN', 'positive'),
    ('@isamaradd Dê Glória a Deus! E diga que o resultado do seu esforço é graças a Ele! Sem a presença do Senhor nada podemos fazer.', 'positive'),
    ('@dinhamoraes1 bom que 2 copinhos de cerveja agora reativa a onda de ontem! Kkkkk', 'positive'),
    ('O Ray me conhece a uma semana e parece que a nossa amizade é de anos.', 'positive'),
    ('RT @versosdampb: Dia de luz, festa do sol, um barquinho a deslizar, no macio azul do mar.', 'positive'),
    ('Que festa FODA. Set de 3 horas do #lowception fechando a noite das 5:30 as 8:30 da manha num lugar irado hahaha https://t.co/oUbt5zrh47', 'positive'),
    ('A humildade é a parte mais bela da sabedoria.', 'positive'),
    ('RT @FoxSports_br: Já já começa o segundo tempo do jogo de despedida de Rogério Ceni! A festa continua no Morumbi! #PraSempreM1TO https://t.…', 'positive'),
    ('RT @bibssouza: Fiz amizade c tanta gente legal', 'positive'),
    ('RT @RecitoBobMarIey: Consciência limpa é a melhor coisa. A paz de encostar a cabeça no travesseiro e ficar tranquilo com as próprias atitud…', 'positive'),
    ('Bom dia! Graça e paz seja contigo.', 'positive'),
    ('RT @projetoshadow: não importa a sua preferência, ambos os cast são ótimos e merecem o nosso carinho e respeito #1MonthToShadowhunters http…', 'positive'),
    ('RT @DREWITHITS: eu espero q ano q vem entre alguém bem foda das galaxia lá na escola pra nós fazer amizade #askbelieber"esperamos', 'positive'),
    ('RT @AsVodkas: Aponta pra festa open bar e rema.', 'positive'),
    ('O melhor de ir pra festa é ir pra incomodar', 'positive'),
    ('RT @ItagibaFrancez: Essa cena eu não via a 30 anos e ontem tive a felicidade de relembrar um pouco do passado !! Muito obrigado ! https://t…', 'positive'),
    ('RT @VladimirAlves: Dinheiro é bom, ajuda, faz rir? Claro! Mas ter amor e respeito pelo próximo e animais, te fazem uma milionária na vida r…', 'positive'),
    ('@ashpurpurina boa festa irmã! Tomara q aconteça uns bafão pra depois vc me contar', 'positive'),
    ('RT @mtnaikkk: "Na alegria e na tristeza é você e eu, na saúde ou na doença você e eu. Ah é só você e eu" Feliz dia 12 minha linda @eloaney', 'positive'),
    ('Parabéns Silvio Santos esse merece meu respeito... Desejo toda felicidade.', 'positive'),
    ('Publiquei 19 fotos no Facebook no álbum "FESTA DA TIA TAI- A GRANDE FAMÍLIA! AUHAUHAUAHUAHUAHUAHUA!" https://t.co/Z37fiZ8iHs', 'positive'),
    ('Uma coisa boa da crise: se bebe (cerveja) e se come (churrasco) menos. A saúde agradece.', 'positive'),
    ('RT @JOAQUINTDASILVA: APROVEITEM O FINAL DE SEMANA COM RESPONSABILIDADE: NÃO USEM DROGAS, E SE SAIREM COM PROSTITUTAS OU TRAVESTIS USEM PRES…', 'positive'),
    ('RT @admnews: 7 dicas para montar uma apresentação de sucesso em pouco tempo https://t.co/ba5TRvoRPh', 'positive'),
    ('RT @CrlAdrielle: Bud é melhor cerveja!!', 'positive'),
    ('Queria esboçar a felicidade q eu estou por ter acabado o curso', 'positive'),
    ('Eu sigo! já aguardando! essa marca vai bombar!!! https://t.co/un4vxLzshx', 'positive'),
    ('john mayer nao tem uma musica ruim mano', 'positive'),
    ('RT @selectionado: isso é lindo, feio é o preconceito https://t.co/wdKLRHZgTx', 'positive'),
    ('Eu achava meu pé feio, mais depois de olhar os pés desses gringos to feliz com o meu. Kkk', 'positive'),
    ('É ela que me intende sempre.', 'positive'),
    ('Meu amor , vou sentir muitas saudades.', 'positive'),
    ('Achei que 2015 ia ser o pior ano da minha vida, mas esta sendo tão bom esse finalzinho', 'positive'),
    ('RT @poxavidanessa: Literalmente todo mundo cometeu pecado nessa festa ahahah', 'positive'),
    ('A felicidade do @thiaguinhocomth  no Snap é contagiante ThiaguinhoNoEsquenta', 'positive'),
    ('@CeConcp @leonecir @LimaCrasto @lourdesGs2 @fabiocharles7 a paz em Cristo uma boa tarde', 'positive'),
    ('RT @1Staalker: Queria voltar no tempo só pra bjar duas boquinh que me conquistaram na festa', 'positive'),
    ('RT @BrasilLM: "As garotas foram fotografadas em várias festas, mandando a mensagem clara que homens vem e vão, mas a amizade delas é para s…', 'positive'),
    ('@lindalima1 Muito obrigada por compartilhar meu vídeo! Bjs', 'positive'),
    ('RT @ternuras_: Dia 20/DEZ na Ternuras Fest - ENTRADA LIBERADA de bebida, COMBOS BARATINHOS lá dentro. Roda de Samba dos T, Junior Paixão e …', 'positive'),
    ('#bomgosteiros #hoje estaremos na Festa da Rádio @maniadobrasil em #Araruama e mais tarde na nossa… https://t.co/BLLI2wUk6c', 'positive'),
    ('O bom de vir em festa na casa da vizinha é que meu Wi-Fi continua pegando #MTVStars Justin Bieber', 'positive'),
    ('RT @tininhoscfc: Quero parabenizar @BrunoRegoBG e toda sua equipe pelo sucesso do  @VillaMixRecife ', 'positive'),
    ('Excelência em todos os detalhes, realme…', 'positive'),
    ('@lucasfresno @fresnorock domingo bom matando a saudade https://t.co/KqQcCZjKKT', 'positive'),
    ('RT @fcsaikomene: feliz um ano de amizade', 'positive'),
    ('@Xinimworld @xininzinha @Cellbitcoxinha @tawaneiros @cascagui @Seusorrisolipe amo vcs d+', 'positive'),
    ('Tu é aquela sensação de paz no meio do caos, ta ligado?', 'positive'),
    ('RT @eususanavieira: Bom dia amiguinhos twitterinhos!!! Que o nosso domingo seja de paz e de muito amor...', 'positive'),
    ('RT @1992svotacoes: Parabéns para ela! Somos todos gratos pelo carinho com a Selena nesses 8 anos de amizade #HappyBirthdayTaylor https://t.…', 'positive'),
    ('RT @AlisonTheodoro: "Parabéns pelo seu sucesso, você é um fenômeno", @celsoportiolli sobre os vídeos de @Kefera #DomingoLegal https://t.co/…', 'positive'),
    ('Acoordei, que festa foi essaaaa', 'positive'),
    ('RT @TIMBrasil: A edição do TIMmusic Na Estrada foi um sucesso. Perdeu ou quer ver de novo, assista aqui: https://t.co/QSSNXrxUma https://t.…', 'positive'),
    ('Camila Queiroz e Agatha Moreira se divertem em festa no Rio https://t.co/5RpfTgARYH', 'positive'),
    ('#domingolegal Maysa é um sucesso em tudo! Claro que o time dela vai ganhar!', 'positive'),
    ('RT @MomTomlinson: Uma mulher decidida que não depende de homem nenhum pra se encontrar. Essa eu respeito.  LuteComoIzzy', 'positive'),
    ('RT @inspirou: Amor de verdade é amizade.', 'positive'),
    ('@mignwlet QUE SAUDADE AMOR ESTOU SABENDO QUE NO DEPARTAMENTO MEDICO TUDO É LINDO', 'positive'),
    ('Compras de Natal feitas com sucesso ;-) #VinhosdoItaliano @ Caminho… https://t.co/gbdpe78Jz4', 'positive'),
    ('OBRIGADAAAA MEU DEUS!!! Obrigada a todos os meus familiares e amigos pela linda festa surpresa de… https://t.co/9vLpbrTagW', 'positive'),
    ('A vida tem me dado tantos presentes Lindus e um presente precioso que ganhei é a amizade… https://t.co/eweD67gE0W', 'positive'),
    ('RT @geCauduro: felicidade é poder estar com quem voce gosta em algum lugar', 'positive'),
    ('As coisas vão dar certo. Vai ter amor, vai ter fé, vai ter paz.', 'positive'),
    ('A Palavra de CRISTO permanece em vós, com toda sua riqueza, de sorte que c/ toda sabedoria possais intruir e exortar-vos mutuamente. Cl3,16a', 'positive'),
    ('RT @LittleMixBR: “Minha amizade com a Jade, Jesy e Leigh esse ano se tornou ainda mais forte. Elas são as garotas mais incriveis" - Perrie …', 'positive'),
    ('RT @ProjetoFFans: Estou tão orgulhosa,pq esse álbum está sendo um sucesso e está batendo vários records, e isso é muito importante pro jb #…', 'positive'),
    ('RT @SignosDeHoje: #Capricórnio Quero paz na alma, sossego na mente, e calma no coração.', 'positive'),
    ('A mais sensata opinião que ouço a respeito desde então ! https://t.co/PzD315aJrb', 'positive'),
    ('Amor próprio é a melhor escolha', 'positive'),
    ('RT @seepussy: Ai caralho que felicidade', 'positive'),
    ('Afim de ir p uma festa só p dançar', 'positive'),
    ('RT @daimacedofaclub: Gente que lindo esse vídeo com a nossa musa proporcionando um momento de alegria e felicidade… https://t.co/G6mEtOvIim', 'positive'),
    ('RT @Oficial_gabimc: Festa surpresaaaaaa!!!!!! https://t.co/c7hpN8VJsB', 'positive'),
    ('Não consigo mais parar de dormir a festa ontem foi massa e me cansou', 'positive'),
    ('RT @mainazita: sou apaixonada pela minha amizade com a Laryssa. pode se passar anos, podemos brigar 400x, mas qnd gnt se encontra de novo é…', 'positive'),
    ('Esta menina tem uma paciência de santa comigo @susanacfsoares https://t.co/brBwZASqqk', 'positive'),
    ('@AmandaPaixao23 fui na mesma festa que o meu, ele é mais lindo pessoalmente, caracaaaa', 'positive'),
    ('Festa ontem foi maraa', 'positive'),
    ('Opala Comodoro é paixão de jovem que ganhou o carro de amigos, em PE https://t.co/zHLxJIvpa0', 'positive'),
    ('@MuriloCleto essa manchete determinou o sucesso do rolê https://t.co/NOrB4Wv08W', 'positive'),
    ('RT @jornalistavitor: Boa tarde @WaldenirXavier Bom domingo. Uma semana com grandes realizações. Sucesso. Um abraço.', 'positive'),
    ('Meu negão faz 1 ano , muita saúde , paz , alegria. Meu mínimo mimado, amo muito , mudinha vida ,Parabéns Miguel', 'positive'),
    ('RT @remembervitti: Olha a felicidade do nosso menino sol https://t.co/rM2FAT6Hlv', 'positive'),
    ('Sinceramente, não teve um a partir do desafio das 6 cadeias que eu não gostei, eu gostei de t o d o s', 'positive'),
    ('RT @ClaudiaLeitte: Mãe mandou orgulhosa! Valeu @atarde! A caminho do #MelhoresDoAno, Pq o amor de vcs já me levou à essa festa linda!! http…', 'positive'),
    ('RT @macmarcoaurelio: Festa é assim. Um Mito e vários protagonistas. O SPFC se junta e se torna maior mesmo com perdas https://t.co/zeRjes83…', 'positive'),
    ('O @AvioesdoForro_ é uma banda muito conhecida aqui no Ceará e no Brasil. Com o vocalistas @SolAlmeidaa e @xandnax. Parabéns pelo sucesso!', 'positive'),
    ('RT @aspositividade: Se um dia, a nossa luz da amizade se apagar, foda-se irmão, a gente acende uma vela.', 'positive'),
    ('Quero muito uma festa em que esteja todos os meus amigos para que eu possa estar com todos  e me divertir com todos', 'positive'),
    ('E quando o amor e a amizade são verdadeiras a distância não atrapalha esses sentimentos.', 'positive'),
    ('Vai começar amizade colorida, melhor filme!!', 'positive'),
    ('O que dizer de uma festa que tem hambúrguer do whata ali sem fila, rapidinho na sua mão? Claro que comi pacas', 'positive'),
    ('A memória de uma amizade verdadeira é como uma canção favorita. Não importa quantas vezes toque no rádio, você nunca vai se cansar dela!!!', 'positive'),
    ('DESENROLEI BAR MEN P MINHA FESTA, SOU MUITO PICA COMO DIZ MATHEUS', 'positive'),
    ('RT @turquim5: Pelo Facebook, o ídolo argentino, Maradona, postou mensagem de solidariedade a Dilma: "Meu coração está contigo" https://t.co…', 'positive'),
    ('RT @hometolarry: a vida é linda mas essa amizade é mais https://t.co/juItKhx6nh', 'positive'),
    ('@halebftz mas eh a amor de idolo o seu eh amor de amizade eu amo os doissss muito', 'positive'),
    ('RT @santovittante: Melhor parte foi ver a felicidade do Rafael e da Isabella quando o outro ganhou,que amor RafaVittiNossoMelhorDoAno', 'positive'),
    ('@kindanamia relaxa Ale, sua princesa vai vir linda e cheia de saúde pra te dar muitas alegrias', 'positive'),
    ('Eu acredito no sol mesmo em dia de nuvens; Eu acredito no amor mesmo quando não o sinto; Eu acredito em Deus mesmo ele estando em silêncio .', 'positive'),
    ('Minha festa de 18 será aqui na casa de praia sim, sim pra caralho', 'positive'),
    ('RT @sorayabborges: DILMASUALINDA TamoJuntim contigo Democraciasimgolpenão #DilmaFica   Parabéns DILMAGUERREIRA saúde proteção sabedoria htt…', 'positive'),
    ('RT @arianacolombo: Como é bom o silêncio de ficar sozinha em casa', 'positive'),
    ('RT @ellencristinav: meu sonho era fazer a maior festa do pijama aqui em casa com tds as meninas do iserj', 'positive'),
    ('O que o @PedroGoMusic acabou de fazer foi lindo! Fez me chorar mas anyways, ele está de parabéns merece todo o respeito.', 'positive'),
    ('Se eu pudesse escolher uma foto para o significado da palavra "felicidade", essa seria uma forte… https://t.co/LG0efCn4fQ', 'positive'),
    ('Goleada nos golpistas...Dilma honrada 7 x 1 Corruptos da Mini-Festação!!! #NaoVaiTerGolpe https://t.co/HTmVvCpFMG', 'positive'),
    ('Sorteio!!! Já que minhas pulseiras de franjas fazem tanto sucesso nas minhas redes sociais e… https://t.co/qkD9pL0VA9', 'positive'),
    ('@gabriel_chalita lindo texto.  Quem tem raízes profundas não é  facilmente abalado! Paz!', 'positive'),
    ('É TANTA FELICIDADE QUE NEM CABE MAIS EM MIM  RafaVittiNossoAtorRevelação', 'positive'),
    ('Vou pro Rio dia 29 chego lá de tarde, ainda bem que vou chegar a tempo da festa da minha tia', 'positive'),
    ('todos falando de amor e respeito, que lindo', 'positive'),
    ('RT @SecretsRodrigo: #MelhoresDoAno: Giovanna Antonelli faz de cada trabalho um sucesso. Impossível não curtir, admirar e torcer por ela.', 'positive'),
    ('"MUITA ESPERANÇA PARA NÓS CONTINUARMOS A CORRER ATRAS DOS NOSSOS SONHOS" ISABELLLAAAA', 'positive'),
    ('RT @belpetit: E, principalmente, não colocamos nossa paz à mercê de ninguém. :)', 'positive'),
    ('RT @ZAMENZA: Momento selfie de #VerdadesSecretas, mais conhecida como o maior sucesso de 2015. Só talentos! S2 #MelhoresdoAno https://t.co/…', 'positive'),
    ('Pai falando pra eu ir na geladeira pegar uma cerveja pra "nós" tomar. Vai chover muito hsusshus', 'positive'),
    ('preciso de uma festa com música eletrônica, daquelas q quando vc percebe vc ja ta dançando pelado junto com um anão em cima da mesa', 'positive'),
    ('RT @MeuBotafogo: Ser Botafogo é orgulho Ser Botafogo é paixão Eternamente Alvinegro será o meu coração!', 'positive'),
    ('Queria tanto que a Alinne Moraes ganhasse, mas o que a Giovana disse, ganhou total meu respeito.', 'positive'),
    ('RT @NauticoNET1998: A Nauticonet parabeniza Edno pela humildade e mesmo após a derrota falou em união, paz... Não atacou ninguém!... https:…', 'positive'),
    ('"Para um mundo com muito mais paz e compaixão. Que a gente enxergue mais o outro"', 'positive'),
    ('Hoje é dia de festa. Hoje é aniversário de ourinhos https://t.co/W73SvzwHxS', 'positive'),
    ('RT @donacallas: Acabou o programa, sugiro que a Globo sirva os pro secos que sobraram aqui no twitter. Pra festa continuar!', 'positive'),
    ('gente já tô com ideias de várias coisinhas pra minha festa', 'positive'),
    ('@catteguarana não vou para nenhuma festa... Arranjei melhor ahaha', 'positive'),
    ('RT @LukasMarqs: Estou com um puta nó na garganta, com o choro preso... De felicidade! Obg a todos vcs', 'positive'),
    ('Cynthia toda animada pra minha famosa festa a fantasia, ainda tá cheia de idéias KKKKKKKKKK eu amo essa minha amiga', 'positive'),
    ('RT @adorofrio: A paz mais bonita do mundo é estar no seu abraço.', 'positive'),
    ('meu primo me deu 30$ ontem pq eu fui o "bar men" da festa dele', 'positive'),
    ('RT @andressajhonson: Não existe imagem melhor do que ver os olhinhos de Anitta brilhando de felicidade e o sorriso indo de orelha à orelha.…', 'positive'),
    ('Festa do pijama ontem, melhor de todas', 'positive'),
    ('RT @CamilaQDaily: Camila desejou ao nosso mundo mais paz, amor e respeito ao próximo! OMundoÉSeuCamilaQ https://t.co/NjSrF91X6w', 'positive'),
    ('@Carolarocca acredite miga!! Fechei esse ano com sucesso Ahahahahahhahhahaha', 'positive'),
    ('@gusttcosta sim, geralmente sim! Mesmo não ganhando vc faz sucesso. Olha o Fifth Harmony!', 'positive'),
    ('RT @SouPositividade: Vem paz, vem amor, vem felicidades, vem energias boas.', 'positive'),
    ('RT @beco_oficial: "Uma pessoa triste tentando fazer outra pessoa triste sorrir. Isso se chama amizade, a verdadeira amizade." | A Menina qu…', 'positive'),
    ('RT @ThiagoNovo50: Agora sim é a nossa, dia 16 é a grande festa da democracia #NaoVaiTerGolpe #ChupaGlobo', 'positive'),
    ('Atingimos e superamos a meta.  Foi um esquenta de SUCESSO.', 'positive'),
    ('como disse eh só sucesso meu povo WATCH SWEATER WEATHER ON VEVO https://t.co/UXgVeB2z40', 'positive'),
    ('RT @sdmulherrn: #ProjetoMulheresDoAxé na Cidade da Esperança no dia 10/12/15: várias modalidades em uma única aula. #BomD+ https://t.co/xWB…', 'positive'),
    ('CARALHO VIADO EU TO BUGANDO TANTO QUE FELICIDADE #1MILHAOEDGE', 'positive'),
    ('RT @Mariahminaj7: Lauren me faz ainda ter esperança na humanidade #WeLoveYouLauren https://t.co/lNW47Livut', 'positive'),
    ('To só esperando a famosa janta pra dormir em paz e dar como terminado o domingo', 'positive'),
    ('RT @PRASEMPREM1TO: Consegue uma festa assim na sua arena pocket? #PraSempreM1TO https://t.co/97pkRN33Ff', 'positive'),
    ('RT @ThalitaToledom: @4thImpactMusic Vocês merecem o sucesso que estão tendo. E tenho certeza que ainda virão muitas coisas boas. #LOVE4thIm…', 'positive'),
    ('Eu não vou deixar nada tirar minha felicidade. #Casamento #Best… https://t.co/FZ3sHeZafR', 'positive'),
    ('RT @Dgrok10: É de uma amizade que surge um amor !', 'positive'),
    ('ta tendo festa aq em casa, amnh eh niver da Minha tia e dps do meu pai', 'positive'),
    ('@JpRufinoOficial  Espero vê-lo em breve na telinha, Sucesso Jp!', 'positive'),
    ('RT @topsjauregui: A melhor coisa da Lauren é a maturidade dela, ela tem 19 anos e a forma dela de pensar e agir sobre o mundo é incrível #W…', 'positive'),
    ('RT @JonaoElire: Jesus não é somente um amigo. É um mestre de verdade e de vida, que revela o caminho para alcançar a felicidade.', 'positive'),
    ('RT @evpcosta_73: Cássia Kis me representa e sempre me representou... admiração ainda maior por essa digna atriz https://t.co/KJgmHQm6Lx', 'positive'),
    ('RT @curiosiddades: Você percebe que encontrou a felicidade quando encontra uma pessoa que gosta de tudo em você, até do seus defeitos.', 'positive'),
    ('@anna_bfr amiga, meu aniversário é primeiro q o seu. Então faz uma festa surpresa p mim q eu faço p você ! Kkkkk', 'positive'),
    ('RT @Esp_Interativo: A torcida do @BVB já está em clima natalino! Que festa ESPETACULAR!', 'positive'),
    ('Festa do Instituto Neymar Jr. reúne mais de 5 mil pessoas e muita música: Artistas como Henrique e Diego e Ale... https://t.co/psbdBKAgjp', 'positive'),
    ('Cientistas têm sucesso com os primeiros cães de proveta nos Estados Unidos https://t.co/tOtpPbA0ZL', 'positive'),
    ('RT @Aguinaldinho: Giovanna Antonelli transforma qualquer personagem em um verdadeiro sucesso. Fenômeno! #MelhoresdoAno https://t.co/5oRzXXV…', 'positive'),
    ('Ontem eu fui em uma festa com esse amigo gostoso do meu pai, nossa queria cumprimentar ele toda hora', 'positive'),
    ('Descoberta feliz da semana: tem um golden de 5 meses morando na minha rua', 'positive'),
    ('RT @inspirou: Felicidade é quando a boca é pequena demais pro tamanho do sorriso que tua alma quer dar.', 'positive'),
    ('RT @jajavital: @MundoDeViajante muito obrigada, já virei fã e desejo muuuito sucesso ao blog! Se depender da minha torcida, já é sucesso!', 'positive'),
    ('Irmãos empresários milionários, cuja fonte de riqueza vem de uma empresa SEM FINS LUCRATIVOS e da saúde pública.... https://t.co/4kQqHwDCmp', 'positive'),
    ('Ae Fernando Souza , força foco e fe....!! tamu junto no aprendizado! https://t.co/I1Q6P2uvxl', 'positive'),
    ('RT @luacardosod: mulher que me der paz vai ficar com a moral em alta', 'positive'),
    ('Amor ao próximo, humildade e caráter.... Isso importa pra nós! Aqui somos todos irmãos, todos por um só objetivo: A caridade e a paz!', 'positive'),
    ('@gutawnn olha miga, geralmente essa festa é um arraso, danço horrores inclusive', 'positive'),
    ('Felicidade é deitar sob lençóis limpos, logo após o banho que acontece ao fim de um delicioso dia de praia.', 'positive'),
    ('Fora as traduções de músicas e uns animes aí podemos dizer que sim, já usei japonês na vida prática. Nenhum aprendizado é em vão.', 'positive'),
    ('Sei que terei mais lá no céu, terei muito mais lá no céu, e uma verdadeira vida aqui, perto de ti, felicidade sem fim...', 'positive'),
    ('RT @lolbazem: saibam que maturidade é algo extremamente atrativo numa pessoa', 'positive'),
    ('@alencraziando que: bom, sinal de que o lacre vai fazer sucesso', 'positive'),
    ('Um dica pra vc que quer ver um filme::: ESCOLHA UM FILME QUE TENHA UM PERSONAGEM GATO,VAI POR MIM VALE A PENA!!!!', 'positive'),
    ('Tenho uma paixão inexplicável pela Marta, ô mulher pra jogar bem', 'positive'),
    ('Agora posso tweetar em paz kkkkkkkkk ManuGavassiNoEncontro', 'positive'),
    ('depois do sucesso do "prots, o protesto passinho", vem ai a continuação da saga: "prots a revanche: o protescomprinha continua"', 'positive'),
    ('RT @depjorgesolla: Ao fim de mais este gigante desafio de sua vida, @dilmabr entrará definitivamente para a história do Brasil como mulher …', 'positive'),
    ('Logo logo fazer umas festa pra inaugurar a nova parte da casa..', 'positive'),
    ('Aplicativo auxilia no aprendizado de português por crianças surdas https://t.co/pYHtxGTCyK via @agenciabrasil', 'positive'),
    ('RT @1XBacon: FELIZ ANIVERSARIOOOOOOOOOOOOOOOOOO TUDO DE BOM PRA VC, MTAS FESTA, MTAS COMIDA, MTS EU, FELICIDADES @matfassarella', 'positive'),
    ('final de semana foi foda!!  Muito Reggae e paz!!', 'positive'),
    ('@oThiagoServo @YouTube Gosto muito desta. Todas suas composições são belíssimas. Isso é dom, dom de Deus. Parabéns e muito sucesso !', 'positive'),
    ('RT @timebrasil: Judô brasileiro se despede de 2015 com Super Desafio contra a Venezuela https://t.co/BLn4xTdPOl via @timebrasil', 'positive')
]
    
    
    
